/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * 5GVnGroupConfiguration.h
 *
 * 
 */

#ifndef 5GVnGroupConfiguration_H_
#define 5GVnGroupConfiguration_H_


#include "5GVnGroupData.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  5GVnGroupConfiguration
{
public:
    5GVnGroupConfiguration();
    virtual ~5GVnGroupConfiguration();

    void validate();

    /////////////////////////////////////////////
    /// 5GVnGroupConfiguration members

    /// <summary>
    /// 
    /// </summary>
    5GVnGroupData getR5gVnGroupData() const;
    void setR5gVnGroupData(5GVnGroupData const& value);
    bool r5gVnGroupDataIsSet() const;
    void unsetr_5gVnGroupData();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getMembers();
    void setMembers(std::vector<std::string> const& value);
    bool membersIsSet() const;
    void unsetMembers();
    /// <summary>
    /// 
    /// </summary>
    int32_t getReferenceId() const;
    void setReferenceId(int32_t const value);
    bool referenceIdIsSet() const;
    void unsetReferenceId();
    /// <summary>
    /// 
    /// </summary>
    std::string getAfInstanceId() const;
    void setAfInstanceId(std::string const& value);
    bool afInstanceIdIsSet() const;
    void unsetAfInstanceId();
    /// <summary>
    /// 
    /// </summary>
    std::string getInternalGroupIdentifier() const;
    void setInternalGroupIdentifier(std::string const& value);
    bool internalGroupIdentifierIsSet() const;
    void unsetInternalGroupIdentifier();
    /// <summary>
    /// 
    /// </summary>
    std::string getMtcProviderInformation() const;
    void setMtcProviderInformation(std::string const& value);
    bool mtcProviderInformationIsSet() const;
    void unsetMtcProviderInformation();

    friend void to_json(nlohmann::json& j, const 5GVnGroupConfiguration& o);
    friend void from_json(const nlohmann::json& j, 5GVnGroupConfiguration& o);
protected:
    5GVnGroupData m_r_5gVnGroupData;
    bool m_r_5gVnGroupDataIsSet;
    std::vector<std::string> m_Members;
    bool m_MembersIsSet;
    int32_t m_ReferenceId;
    bool m_ReferenceIdIsSet;
    std::string m_AfInstanceId;
    bool m_AfInstanceIdIsSet;
    std::string m_InternalGroupIdentifier;
    bool m_InternalGroupIdentifierIsSet;
    std::string m_MtcProviderInformation;
    bool m_MtcProviderInformationIsSet;
};

}
}
}
}

#endif /* 5GVnGroupConfiguration_H_ */
