/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Arp.h
 *
 * 
 */

#ifndef Arp_H_
#define Arp_H_


#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Arp
{
public:
    Arp();
    virtual ~Arp();

    void validate();

    /////////////////////////////////////////////
    /// Arp members

    /// <summary>
    /// 
    /// </summary>
    Object getPriorityLevel() const;
    void setPriorityLevel(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    Object getPreemptCap() const;
    void setPreemptCap(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    Object getPreemptVuln() const;
    void setPreemptVuln(Object const& value);

    friend void to_json(nlohmann::json& j, const Arp& o);
    friend void from_json(const nlohmann::json& j, Arp& o);
protected:
    Object m_PriorityLevel;

    Object m_PreemptCap;

    Object m_PreemptVuln;

};

}
}
}
}

#endif /* Arp_H_ */
