/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * BdtPolicyData.h
 *
 * 
 */

#ifndef BdtPolicyData_H_
#define BdtPolicyData_H_


#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  BdtPolicyData
{
public:
    BdtPolicyData();
    virtual ~BdtPolicyData();

    void validate();

    /////////////////////////////////////////////
    /// BdtPolicyData members

    /// <summary>
    /// 
    /// </summary>
    Object getInterGroupId() const;
    void setInterGroupId(Object const& value);
    bool interGroupIdIsSet() const;
    void unsetInterGroupId();
    /// <summary>
    /// 
    /// </summary>
    Object getSupi() const;
    void setSupi(Object const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// 
    /// </summary>
    Object getBdtRefId() const;
    void setBdtRefId(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    Object getDnn() const;
    void setDnn(Object const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    Object getSnssai() const;
    void setSnssai(Object const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// 
    /// </summary>
    Object getResUri() const;
    void setResUri(Object const& value);
    bool resUriIsSet() const;
    void unsetResUri();

    friend void to_json(nlohmann::json& j, const BdtPolicyData& o);
    friend void from_json(const nlohmann::json& j, BdtPolicyData& o);
protected:
    Object m_InterGroupId;
    bool m_InterGroupIdIsSet;
    Object m_Supi;
    bool m_SupiIsSet;
    Object m_BdtRefId;

    Object m_Dnn;
    bool m_DnnIsSet;
    Object m_Snssai;
    bool m_SnssaiIsSet;
    Object m_ResUri;
    bool m_ResUriIsSet;
};

}
}
}
}

#endif /* BdtPolicyData_H_ */
