/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CagData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CagData::CagData()
{
    m_ProvisioningTime = "";
    m_ProvisioningTimeIsSet = false;
    
}

CagData::~CagData()
{
}

void CagData::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const CagData& o)
{
    j = nlohmann::json();
    j["cagInfos"] = o.m_CagInfos;
    if(o.provisioningTimeIsSet())
        j["provisioningTime"] = o.m_ProvisioningTime;
}

void from_json(const nlohmann::json& j, CagData& o)
{
    j.at("cagInfos").get_to(o.m_CagInfos);
    if(j.find("provisioningTime") != j.end())
    {
        j.at("provisioningTime").get_to(o.m_ProvisioningTime);
        o.m_ProvisioningTimeIsSet = true;
    } 
}

std::map<std::string, CagInfo>& CagData::getCagInfos()
{
    return m_CagInfos;
}
void CagData::setCagInfos(std::map<std::string, CagInfo> const& value)
{
    m_CagInfos = value;
}
std::string CagData::getProvisioningTime() const
{
    return m_ProvisioningTime;
}
void CagData::setProvisioningTime(std::string const& value)
{
    m_ProvisioningTime = value;
    m_ProvisioningTimeIsSet = true;
}
bool CagData::provisioningTimeIsSet() const
{
    return m_ProvisioningTimeIsSet;
}
void CagData::unsetProvisioningTime()
{
    m_ProvisioningTimeIsSet = false;
}

}
}
}
}

