/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CodeWordInd.h
 *
 * 
 */

#ifndef CodeWordInd_H_
#define CodeWordInd_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CodeWordInd
{
public:
    CodeWordInd();
    virtual ~CodeWordInd();

    void validate();

    /////////////////////////////////////////////
    /// CodeWordInd members


    friend void to_json(nlohmann::json& j, const CodeWordInd& o);
    friend void from_json(const nlohmann::json& j, CodeWordInd& o);
protected:
};

}
}
}
}

#endif /* CodeWordInd_H_ */
