/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DataFilter.h
 *
 * Identifies a data filter.
 */

#ifndef DataFilter_H_
#define DataFilter_H_


#include "Object.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Identifies a data filter.
/// </summary>
class  DataFilter
{
public:
    DataFilter();
    virtual ~DataFilter();

    void validate();

    /////////////////////////////////////////////
    /// DataFilter members

    /// <summary>
    /// 
    /// </summary>
    Object getDataInd() const;
    void setDataInd(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getDnns();
    void setDnns(std::vector<Object> const& value);
    bool dnnsIsSet() const;
    void unsetDnns();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getSnssais();
    void setSnssais(std::vector<Object> const& value);
    bool snssaisIsSet() const;
    void unsetSnssais();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getInternalGroupIds();
    void setInternalGroupIds(std::vector<Object> const& value);
    bool internalGroupIdsIsSet() const;
    void unsetInternalGroupIds();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getSupis();
    void setSupis(std::vector<Object> const& value);
    bool supisIsSet() const;
    void unsetSupis();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getAppIds();
    void setAppIds(std::vector<Object> const& value);
    bool appIdsIsSet() const;
    void unsetAppIds();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getUeIpv4s();
    void setUeIpv4s(std::vector<Object> const& value);
    bool ueIpv4sIsSet() const;
    void unsetUeIpv4s();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getUeIpv6s();
    void setUeIpv6s(std::vector<Object> const& value);
    bool ueIpv6sIsSet() const;
    void unsetUeIpv6s();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getUeMacs();
    void setUeMacs(std::vector<Object> const& value);
    bool ueMacsIsSet() const;
    void unsetUeMacs();

    friend void to_json(nlohmann::json& j, const DataFilter& o);
    friend void from_json(const nlohmann::json& j, DataFilter& o);
protected:
    Object m_DataInd;

    std::vector<Object> m_Dnns;
    bool m_DnnsIsSet;
    std::vector<Object> m_Snssais;
    bool m_SnssaisIsSet;
    std::vector<Object> m_InternalGroupIds;
    bool m_InternalGroupIdsIsSet;
    std::vector<Object> m_Supis;
    bool m_SupisIsSet;
    std::vector<Object> m_AppIds;
    bool m_AppIdsIsSet;
    std::vector<Object> m_UeIpv4s;
    bool m_UeIpv4sIsSet;
    std::vector<Object> m_UeIpv6s;
    bool m_UeIpv6sIsSet;
    std::vector<Object> m_UeMacs;
    bool m_UeMacsIsSet;
};

}
}
}
}

#endif /* DataFilter_H_ */
