/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EnhancedCoverageRestrictionData.h
 *
 * 
 */

#ifndef EnhancedCoverageRestrictionData_H_
#define EnhancedCoverageRestrictionData_H_


#include "PlmnEcInfo.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  EnhancedCoverageRestrictionData
{
public:
    EnhancedCoverageRestrictionData();
    virtual ~EnhancedCoverageRestrictionData();

    void validate();

    /////////////////////////////////////////////
    /// EnhancedCoverageRestrictionData members

    /// <summary>
    /// 
    /// </summary>
    std::vector<PlmnEcInfo>& getPlmnEcInfoList();
    void setPlmnEcInfoList(std::vector<PlmnEcInfo> const& value);
    bool plmnEcInfoListIsSet() const;
    void unsetPlmnEcInfoList();

    friend void to_json(nlohmann::json& j, const EnhancedCoverageRestrictionData& o);
    friend void from_json(const nlohmann::json& j, EnhancedCoverageRestrictionData& o);
protected:
    std::vector<PlmnEcInfo> m_PlmnEcInfoList;
    bool m_PlmnEcInfoListIsSet;
};

}
}
}
}

#endif /* EnhancedCoverageRestrictionData_H_ */
