/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IptvConfigData.h
 *
 * 
 */

#ifndef IptvConfigData_H_
#define IptvConfigData_H_


#include <string>
#include "Object.h"
#include <map>
#include <vector>
#include "AnyType.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  IptvConfigData
{
public:
    IptvConfigData();
    virtual ~IptvConfigData();

    void validate();

    /////////////////////////////////////////////
    /// IptvConfigData members

    /// <summary>
    /// 
    /// </summary>
    Object getSupi() const;
    void setSupi(Object const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// Identifies a group of users.
    /// </summary>
    AnyType getInterGroupId() const;
    void setInterGroupId(AnyType const& value);
    bool interGroupIdIsSet() const;
    void unsetInterGroupId();
    /// <summary>
    /// 
    /// </summary>
    Object getDnn() const;
    void setDnn(Object const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    Object getSnssai() const;
    void setSnssai(Object const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// 
    /// </summary>
    std::string getAfAppId() const;
    void setAfAppId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, Object>& getMultiAccCtrls();
    void setMultiAccCtrls(std::map<std::string, Object> const& value);
    /// <summary>
    /// 
    /// </summary>
    Object getSuppFeat() const;
    void setSuppFeat(Object const& value);
    bool suppFeatIsSet() const;
    void unsetSuppFeat();
    /// <summary>
    /// 
    /// </summary>
    Object getResUri() const;
    void setResUri(Object const& value);
    bool resUriIsSet() const;
    void unsetResUri();

    friend void to_json(nlohmann::json& j, const IptvConfigData& o);
    friend void from_json(const nlohmann::json& j, IptvConfigData& o);
protected:
    Object m_Supi;
    bool m_SupiIsSet;
    AnyType m_InterGroupId;
    bool m_InterGroupIdIsSet;
    Object m_Dnn;
    bool m_DnnIsSet;
    Object m_Snssai;
    bool m_SnssaiIsSet;
    std::string m_AfAppId;

    std::map<std::string, Object> m_MultiAccCtrls;

    Object m_SuppFeat;
    bool m_SuppFeatIsSet;
    Object m_ResUri;
    bool m_ResUriIsSet;
};

}
}
}
}

#endif /* IptvConfigData_H_ */
