/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "IptvConfigData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

IptvConfigData::IptvConfigData()
{
    m_SupiIsSet = false;
    m_InterGroupIdIsSet = false;
    m_DnnIsSet = false;
    m_SnssaiIsSet = false;
    m_AfAppId = "";
    m_SuppFeatIsSet = false;
    m_ResUriIsSet = false;
    
}

IptvConfigData::~IptvConfigData()
{
}

void IptvConfigData::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const IptvConfigData& o)
{
    j = nlohmann::json();
    if(o.supiIsSet())
        j["supi"] = o.m_Supi;
    if(o.interGroupIdIsSet())
        j["interGroupId"] = o.m_InterGroupId;
    if(o.dnnIsSet())
        j["dnn"] = o.m_Dnn;
    if(o.snssaiIsSet())
        j["snssai"] = o.m_Snssai;
    j["afAppId"] = o.m_AfAppId;
    j["multiAccCtrls"] = o.m_MultiAccCtrls;
    if(o.suppFeatIsSet())
        j["suppFeat"] = o.m_SuppFeat;
    if(o.resUriIsSet())
        j["resUri"] = o.m_ResUri;
}

void from_json(const nlohmann::json& j, IptvConfigData& o)
{
    if(j.find("supi") != j.end())
    {
        j.at("supi").get_to(o.m_Supi);
        o.m_SupiIsSet = true;
    } 
    if(j.find("interGroupId") != j.end())
    {
        j.at("interGroupId").get_to(o.m_InterGroupId);
        o.m_InterGroupIdIsSet = true;
    } 
    if(j.find("dnn") != j.end())
    {
        j.at("dnn").get_to(o.m_Dnn);
        o.m_DnnIsSet = true;
    } 
    if(j.find("snssai") != j.end())
    {
        j.at("snssai").get_to(o.m_Snssai);
        o.m_SnssaiIsSet = true;
    } 
    j.at("afAppId").get_to(o.m_AfAppId);
    j.at("multiAccCtrls").get_to(o.m_MultiAccCtrls);
    if(j.find("suppFeat") != j.end())
    {
        j.at("suppFeat").get_to(o.m_SuppFeat);
        o.m_SuppFeatIsSet = true;
    } 
    if(j.find("resUri") != j.end())
    {
        j.at("resUri").get_to(o.m_ResUri);
        o.m_ResUriIsSet = true;
    } 
}

Object IptvConfigData::getSupi() const
{
    return m_Supi;
}
void IptvConfigData::setSupi(Object const& value)
{
    m_Supi = value;
    m_SupiIsSet = true;
}
bool IptvConfigData::supiIsSet() const
{
    return m_SupiIsSet;
}
void IptvConfigData::unsetSupi()
{
    m_SupiIsSet = false;
}
AnyType IptvConfigData::getInterGroupId() const
{
    return m_InterGroupId;
}
void IptvConfigData::setInterGroupId(AnyType const& value)
{
    m_InterGroupId = value;
    m_InterGroupIdIsSet = true;
}
bool IptvConfigData::interGroupIdIsSet() const
{
    return m_InterGroupIdIsSet;
}
void IptvConfigData::unsetInterGroupId()
{
    m_InterGroupIdIsSet = false;
}
Object IptvConfigData::getDnn() const
{
    return m_Dnn;
}
void IptvConfigData::setDnn(Object const& value)
{
    m_Dnn = value;
    m_DnnIsSet = true;
}
bool IptvConfigData::dnnIsSet() const
{
    return m_DnnIsSet;
}
void IptvConfigData::unsetDnn()
{
    m_DnnIsSet = false;
}
Object IptvConfigData::getSnssai() const
{
    return m_Snssai;
}
void IptvConfigData::setSnssai(Object const& value)
{
    m_Snssai = value;
    m_SnssaiIsSet = true;
}
bool IptvConfigData::snssaiIsSet() const
{
    return m_SnssaiIsSet;
}
void IptvConfigData::unsetSnssai()
{
    m_SnssaiIsSet = false;
}
std::string IptvConfigData::getAfAppId() const
{
    return m_AfAppId;
}
void IptvConfigData::setAfAppId(std::string const& value)
{
    m_AfAppId = value;
}
std::map<std::string, Object>& IptvConfigData::getMultiAccCtrls()
{
    return m_MultiAccCtrls;
}
void IptvConfigData::setMultiAccCtrls(std::map<std::string, Object> const& value)
{
    m_MultiAccCtrls = value;
}
Object IptvConfigData::getSuppFeat() const
{
    return m_SuppFeat;
}
void IptvConfigData::setSuppFeat(Object const& value)
{
    m_SuppFeat = value;
    m_SuppFeatIsSet = true;
}
bool IptvConfigData::suppFeatIsSet() const
{
    return m_SuppFeatIsSet;
}
void IptvConfigData::unsetSuppFeat()
{
    m_SuppFeatIsSet = false;
}
Object IptvConfigData::getResUri() const
{
    return m_ResUri;
}
void IptvConfigData::setResUri(Object const& value)
{
    m_ResUri = value;
    m_ResUriIsSet = true;
}
bool IptvConfigData::resUriIsSet() const
{
    return m_ResUriIsSet;
}
void IptvConfigData::unsetResUri()
{
    m_ResUriIsSet = false;
}

}
}
}
}

