/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LcsBroadcastAssistanceTypesData.h
 *
 * 
 */

#ifndef LcsBroadcastAssistanceTypesData_H_
#define LcsBroadcastAssistanceTypesData_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LcsBroadcastAssistanceTypesData
{
public:
    LcsBroadcastAssistanceTypesData();
    virtual ~LcsBroadcastAssistanceTypesData();

    void validate();

    /////////////////////////////////////////////
    /// LcsBroadcastAssistanceTypesData members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getLocationAssistanceType();
    void setLocationAssistanceType(std::vector<std::string> const& value);

    friend void to_json(nlohmann::json& j, const LcsBroadcastAssistanceTypesData& o);
    friend void from_json(const nlohmann::json& j, LcsBroadcastAssistanceTypesData& o);
protected:
    std::vector<std::string> m_LocationAssistanceType;

};

}
}
}
}

#endif /* LcsBroadcastAssistanceTypesData_H_ */
