/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LocationPrivacyInd.h
 *
 * 
 */

#ifndef LocationPrivacyInd_H_
#define LocationPrivacyInd_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LocationPrivacyInd
{
public:
    LocationPrivacyInd();
    virtual ~LocationPrivacyInd();

    void validate();

    /////////////////////////////////////////////
    /// LocationPrivacyInd members


    friend void to_json(nlohmann::json& j, const LocationPrivacyInd& o);
    friend void from_json(const nlohmann::json& j, LocationPrivacyInd& o);
protected:
};

}
}
}
}

#endif /* LocationPrivacyInd_H_ */
