/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LoggingDurationMdt.h
 *
 * 
 */

#ifndef LoggingDurationMdt_H_
#define LoggingDurationMdt_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LoggingDurationMdt
{
public:
    LoggingDurationMdt();
    virtual ~LoggingDurationMdt();

    void validate();

    /////////////////////////////////////////////
    /// LoggingDurationMdt members


    friend void to_json(nlohmann::json& j, const LoggingDurationMdt& o);
    friend void from_json(const nlohmann::json& j, LoggingDurationMdt& o);
protected:
};

}
}
}
}

#endif /* LoggingDurationMdt_H_ */
