/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LossConnectivityCfg.h
 *
 * 
 */

#ifndef LossConnectivityCfg_H_
#define LossConnectivityCfg_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LossConnectivityCfg
{
public:
    LossConnectivityCfg();
    virtual ~LossConnectivityCfg();

    void validate();

    /////////////////////////////////////////////
    /// LossConnectivityCfg members

    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxDetectionTime() const;
    void setMaxDetectionTime(int32_t const value);
    bool maxDetectionTimeIsSet() const;
    void unsetMaxDetectionTime();

    friend void to_json(nlohmann::json& j, const LossConnectivityCfg& o);
    friend void from_json(const nlohmann::json& j, LossConnectivityCfg& o);
protected:
    int32_t m_MaxDetectionTime;
    bool m_MaxDetectionTimeIsSet;
};

}
}
}
}

#endif /* LossConnectivityCfg_H_ */
