/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Nssai.h
 *
 * 
 */

#ifndef Nssai_H_
#define Nssai_H_


#include <string>
#include <map>
#include "Snssai.h"
#include <vector>
#include "AdditionalSnssaiData.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Nssai
{
public:
    Nssai();
    virtual ~Nssai();

    void validate();

    /////////////////////////////////////////////
    /// Nssai members

    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Snssai>& getDefaultSingleNssais();
    void setDefaultSingleNssais(std::vector<Snssai> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<Snssai>& getSingleNssais();
    void setSingleNssais(std::vector<Snssai> const& value);
    bool singleNssaisIsSet() const;
    void unsetSingleNssais();
    /// <summary>
    /// 
    /// </summary>
    std::string getProvisioningTime() const;
    void setProvisioningTime(std::string const& value);
    bool provisioningTimeIsSet() const;
    void unsetProvisioningTime();
    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, AdditionalSnssaiData>& getAdditionalSnssaiData();
    void setAdditionalSnssaiData(std::map<std::string, AdditionalSnssaiData> const& value);
    bool additionalSnssaiDataIsSet() const;
    void unsetAdditionalSnssaiData();

    friend void to_json(nlohmann::json& j, const Nssai& o);
    friend void from_json(const nlohmann::json& j, Nssai& o);
protected:
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
    std::vector<Snssai> m_DefaultSingleNssais;

    std::vector<Snssai> m_SingleNssais;
    bool m_SingleNssaisIsSet;
    std::string m_ProvisioningTime;
    bool m_ProvisioningTimeIsSet;
    std::map<std::string, AdditionalSnssaiData> m_AdditionalSnssaiData;
    bool m_AdditionalSnssaiDataIsSet;
};

}
}
}
}

#endif /* Nssai_H_ */
