/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NssaiAckData.h
 *
 * 
 */

#ifndef NssaiAckData_H_
#define NssaiAckData_H_


#include <string>
#include "UeUpdateStatus.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  NssaiAckData
{
public:
    NssaiAckData();
    virtual ~NssaiAckData();

    void validate();

    /////////////////////////////////////////////
    /// NssaiAckData members

    /// <summary>
    /// 
    /// </summary>
    std::string getProvisioningTime() const;
    void setProvisioningTime(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    UeUpdateStatus getUeUpdateStatus() const;
    void setUeUpdateStatus(UeUpdateStatus const& value);

    friend void to_json(nlohmann::json& j, const NssaiAckData& o);
    friend void from_json(const nlohmann::json& j, NssaiAckData& o);
protected:
    std::string m_ProvisioningTime;

    UeUpdateStatus m_UeUpdateStatus;

};

}
}
}
}

#endif /* NssaiAckData_H_ */
