/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PlmnId::PlmnId()
{
    
}

PlmnId::~PlmnId()
{
}

void PlmnId::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const PlmnId& o)
{
    j = nlohmann::json();
    j["mcc"] = o.m_Mcc;
    j["mnc"] = o.m_Mnc;
}

void from_json(const nlohmann::json& j, PlmnId& o)
{
    j.at("mcc").get_to(o.m_Mcc);
    j.at("mnc").get_to(o.m_Mnc);
}

Object PlmnId::getMcc() const
{
    return m_Mcc;
}
void PlmnId::setMcc(Object const& value)
{
    m_Mcc = value;
}
Object PlmnId::getMnc() const
{
    return m_Mnc;
}
void PlmnId::setMnc(Object const& value)
{
    m_Mnc = value;
}

}
}
}
}

