/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PointAltitudeUncertainty_allOf.h
 *
 * 
 */

#ifndef PointAltitudeUncertainty_allOf_H_
#define PointAltitudeUncertainty_allOf_H_


#include "GeographicalCoordinates.h"
#include "UncertaintyEllipse.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PointAltitudeUncertainty_allOf
{
public:
    PointAltitudeUncertainty_allOf();
    virtual ~PointAltitudeUncertainty_allOf();

    void validate();

    /////////////////////////////////////////////
    /// PointAltitudeUncertainty_allOf members

    /// <summary>
    /// 
    /// </summary>
    GeographicalCoordinates getPoint() const;
    void setPoint(GeographicalCoordinates const& value);
    /// <summary>
    /// 
    /// </summary>
    double getAltitude() const;
    void setAltitude(double const value);
    /// <summary>
    /// 
    /// </summary>
    UncertaintyEllipse getUncertaintyEllipse() const;
    void setUncertaintyEllipse(UncertaintyEllipse const& value);
    /// <summary>
    /// 
    /// </summary>
    float getUncertaintyAltitude() const;
    void setUncertaintyAltitude(float const value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getConfidence() const;
    void setConfidence(int32_t const value);

    friend void to_json(nlohmann::json& j, const PointAltitudeUncertainty_allOf& o);
    friend void from_json(const nlohmann::json& j, PointAltitudeUncertainty_allOf& o);
protected:
    GeographicalCoordinates m_Point;

    double m_Altitude;

    UncertaintyEllipse m_UncertaintyEllipse;

    float m_UncertaintyAltitude;

    int32_t m_Confidence;

};

}
}
}
}

#endif /* PointAltitudeUncertainty_allOf_H_ */
