/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Point.h
 *
 * 
 */

#ifndef Point_H_
#define Point_H_


#include "GeographicalCoordinates.h"
#include "Point_allOf.h"
#include "Object.h"
#include "GADShape.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Point
{
public:
    Point();
    virtual ~Point();

    void validate();

    /////////////////////////////////////////////
    /// Point members

    /// <summary>
    /// 
    /// </summary>
    Object getShape() const;
    void setShape(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    GeographicalCoordinates getPoint() const;
    void setPoint(GeographicalCoordinates const& value);

    friend void to_json(nlohmann::json& j, const Point& o);
    friend void from_json(const nlohmann::json& j, Point& o);
protected:
    Object m_Shape;

    GeographicalCoordinates m_Point;

};

}
}
}
}

#endif /* Point_H_ */
