/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ResourceItem.h
 *
 * Identifies a subscription to policy data change notification when the change occurs in a fragment (subset of resource data) of a given resource.
 */

#ifndef ResourceItem_H_
#define ResourceItem_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Identifies a subscription to policy data change notification when the change occurs in a fragment (subset of resource data) of a given resource.
/// </summary>
class  ResourceItem
{
public:
    ResourceItem();
    virtual ~ResourceItem();

    void validate();

    /////////////////////////////////////////////
    /// ResourceItem members

    /// <summary>
    /// 
    /// </summary>
    std::string getMonResourceUri() const;
    void setMonResourceUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getItems();
    void setItems(std::vector<std::string> const& value);

    friend void to_json(nlohmann::json& j, const ResourceItem& o);
    friend void from_json(const nlohmann::json& j, ResourceItem& o);
protected:
    std::string m_MonResourceUri;

    std::vector<std::string> m_Items;

};

}
}
}
}

#endif /* ResourceItem_H_ */
