/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ServiceParameterData.h
 *
 * 
 */

#ifndef ServiceParameterData_H_
#define ServiceParameterData_H_


#include <string>
#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ServiceParameterData
{
public:
    ServiceParameterData();
    virtual ~ServiceParameterData();

    void validate();

    /////////////////////////////////////////////
    /// ServiceParameterData members

    /// <summary>
    /// Identifies an application.
    /// </summary>
    std::string getAppId() const;
    void setAppId(std::string const& value);
    bool appIdIsSet() const;
    void unsetAppId();
    /// <summary>
    /// 
    /// </summary>
    Object getDnn() const;
    void setDnn(Object const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    Object getSnssai() const;
    void setSnssai(Object const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// 
    /// </summary>
    Object getInterGroupId() const;
    void setInterGroupId(Object const& value);
    bool interGroupIdIsSet() const;
    void unsetInterGroupId();
    /// <summary>
    /// 
    /// </summary>
    Object getSupi() const;
    void setSupi(Object const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// 
    /// </summary>
    Object getUeIpv4() const;
    void setUeIpv4(Object const& value);
    bool ueIpv4IsSet() const;
    void unsetUeIpv4();
    /// <summary>
    /// 
    /// </summary>
    Object getUeIpv6() const;
    void setUeIpv6(Object const& value);
    bool ueIpv6IsSet() const;
    void unsetUeIpv6();
    /// <summary>
    /// 
    /// </summary>
    Object getUeMac() const;
    void setUeMac(Object const& value);
    bool ueMacIsSet() const;
    void unsetUeMac();
    /// <summary>
    /// 
    /// </summary>
    bool isAnyUeInd() const;
    void setAnyUeInd(bool const value);
    bool anyUeIndIsSet() const;
    void unsetAnyUeInd();
    /// <summary>
    /// 
    /// </summary>
    Object getParamOverPc5() const;
    void setParamOverPc5(Object const& value);
    bool paramOverPc5IsSet() const;
    void unsetParamOverPc5();
    /// <summary>
    /// 
    /// </summary>
    Object getParamOverUu() const;
    void setParamOverUu(Object const& value);
    bool paramOverUuIsSet() const;
    void unsetParamOverUu();
    /// <summary>
    /// 
    /// </summary>
    Object getSuppFeat() const;
    void setSuppFeat(Object const& value);
    bool suppFeatIsSet() const;
    void unsetSuppFeat();
    /// <summary>
    /// 
    /// </summary>
    Object getResUri() const;
    void setResUri(Object const& value);
    bool resUriIsSet() const;
    void unsetResUri();

    friend void to_json(nlohmann::json& j, const ServiceParameterData& o);
    friend void from_json(const nlohmann::json& j, ServiceParameterData& o);
protected:
    std::string m_AppId;
    bool m_AppIdIsSet;
    Object m_Dnn;
    bool m_DnnIsSet;
    Object m_Snssai;
    bool m_SnssaiIsSet;
    Object m_InterGroupId;
    bool m_InterGroupIdIsSet;
    Object m_Supi;
    bool m_SupiIsSet;
    Object m_UeIpv4;
    bool m_UeIpv4IsSet;
    Object m_UeIpv6;
    bool m_UeIpv6IsSet;
    Object m_UeMac;
    bool m_UeMacIsSet;
    bool m_AnyUeInd;
    bool m_AnyUeIndIsSet;
    Object m_ParamOverPc5;
    bool m_ParamOverPc5IsSet;
    Object m_ParamOverUu;
    bool m_ParamOverUuIsSet;
    Object m_SuppFeat;
    bool m_SuppFeatIsSet;
    Object m_ResUri;
    bool m_ResUriIsSet;
};

}
}
}
}

#endif /* ServiceParameterData_H_ */
