/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ServiceAreaRestriction.h
 *
 * 
 */

#ifndef ServiceAreaRestriction_H_
#define ServiceAreaRestriction_H_


#include "Area.h"
#include "Object.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ServiceAreaRestriction
{
public:
    ServiceAreaRestriction();
    virtual ~ServiceAreaRestriction();

    void validate();

    /////////////////////////////////////////////
    /// ServiceAreaRestriction members

    /// <summary>
    /// 
    /// </summary>
    Object getRestrictionType() const;
    void setRestrictionType(Object const& value);
    bool restrictionTypeIsSet() const;
    void unsetRestrictionType();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Area>& getAreas();
    void setAreas(std::vector<Area> const& value);
    bool areasIsSet() const;
    void unsetAreas();
    /// <summary>
    /// 
    /// </summary>
    Object getMaxNumOfTAs() const;
    void setMaxNumOfTAs(Object const& value);
    bool maxNumOfTAsIsSet() const;
    void unsetMaxNumOfTAs();
    /// <summary>
    /// 
    /// </summary>
    Object getMaxNumOfTAsForNotAllowedAreas() const;
    void setMaxNumOfTAsForNotAllowedAreas(Object const& value);
    bool maxNumOfTAsForNotAllowedAreasIsSet() const;
    void unsetMaxNumOfTAsForNotAllowedAreas();

    friend void to_json(nlohmann::json& j, const ServiceAreaRestriction& o);
    friend void from_json(const nlohmann::json& j, ServiceAreaRestriction& o);
protected:
    Object m_RestrictionType;
    bool m_RestrictionTypeIsSet;
    std::vector<Area> m_Areas;
    bool m_AreasIsSet;
    Object m_MaxNumOfTAs;
    bool m_MaxNumOfTAsIsSet;
    Object m_MaxNumOfTAsForNotAllowedAreas;
    bool m_MaxNumOfTAsForNotAllowedAreasIsSet;
};

}
}
}
}

#endif /* ServiceAreaRestriction_H_ */
