/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SmPolicyData.h
 *
 * Contains the SM policy data for a given subscriber.
 */

#ifndef SmPolicyData_H_
#define SmPolicyData_H_


#include "UsageMonDataLimit.h"
#include <string>
#include "SmPolicySnssaiData.h"
#include <map>
#include <vector>
#include "UsageMonData.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains the SM policy data for a given subscriber.
/// </summary>
class  SmPolicyData
{
public:
    SmPolicyData();
    virtual ~SmPolicyData();

    void validate();

    /////////////////////////////////////////////
    /// SmPolicyData members

    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, SmPolicySnssaiData>& getSmPolicySnssaiData();
    void setSmPolicySnssaiData(std::map<std::string, SmPolicySnssaiData> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, UsageMonDataLimit>& getUmDataLimits();
    void setUmDataLimits(std::map<std::string, UsageMonDataLimit> const& value);
    bool umDataLimitsIsSet() const;
    void unsetUmDataLimits();
    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, UsageMonData>& getUmData();
    void setUmData(std::map<std::string, UsageMonData> const& value);
    bool umDataIsSet() const;
    void unsetUmData();
    /// <summary>
    /// 
    /// </summary>
    std::string getSuppFeat() const;
    void setSuppFeat(std::string const& value);
    bool suppFeatIsSet() const;
    void unsetSuppFeat();

    friend void to_json(nlohmann::json& j, const SmPolicyData& o);
    friend void from_json(const nlohmann::json& j, SmPolicyData& o);
protected:
    std::map<std::string, SmPolicySnssaiData> m_SmPolicySnssaiData;

    std::map<std::string, UsageMonDataLimit> m_UmDataLimits;
    bool m_UmDataLimitsIsSet;
    std::map<std::string, UsageMonData> m_UmData;
    bool m_UmDataIsSet;
    std::string m_SuppFeat;
    bool m_SuppFeatIsSet;
};

}
}
}
}

#endif /* SmPolicyData_H_ */
