/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SteeringInfo.h
 *
 * 
 */

#ifndef SteeringInfo_H_
#define SteeringInfo_H_


#include "AccessTech.h"
#include "Object.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  SteeringInfo
{
public:
    SteeringInfo();
    virtual ~SteeringInfo();

    void validate();

    /////////////////////////////////////////////
    /// SteeringInfo members

    /// <summary>
    /// 
    /// </summary>
    Object getPlmnId() const;
    void setPlmnId(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<AccessTech>& getAccessTechList();
    void setAccessTechList(std::vector<AccessTech> const& value);
    bool accessTechListIsSet() const;
    void unsetAccessTechList();

    friend void to_json(nlohmann::json& j, const SteeringInfo& o);
    friend void from_json(const nlohmann::json& j, SteeringInfo& o);
protected:
    Object m_PlmnId;

    std::vector<AccessTech> m_AccessTechList;
    bool m_AccessTechListIsSet;
};

}
}
}
}

#endif /* SteeringInfo_H_ */
