/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TrafficInfluSub.h
 *
 * 
 */

#ifndef TrafficInfluSub_H_
#define TrafficInfluSub_H_


#include "Object.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  TrafficInfluSub
{
public:
    TrafficInfluSub();
    virtual ~TrafficInfluSub();

    void validate();

    /////////////////////////////////////////////
    /// TrafficInfluSub members

    /// <summary>
    /// Each element identifies a DNN.
    /// </summary>
    std::vector<Object>& getDnns();
    void setDnns(std::vector<Object> const& value);
    bool dnnsIsSet() const;
    void unsetDnns();
    /// <summary>
    /// Each element identifies a slice.
    /// </summary>
    std::vector<Object>& getSnssais();
    void setSnssais(std::vector<Object> const& value);
    bool snssaisIsSet() const;
    void unsetSnssais();
    /// <summary>
    /// Each element identifies a group of users.
    /// </summary>
    std::vector<Object>& getInternalGroupIds();
    void setInternalGroupIds(std::vector<Object> const& value);
    bool internalGroupIdsIsSet() const;
    void unsetInternalGroupIds();
    /// <summary>
    /// Each element identifies the user.
    /// </summary>
    std::vector<Object>& getSupis();
    void setSupis(std::vector<Object> const& value);
    bool supisIsSet() const;
    void unsetSupis();
    /// <summary>
    /// 
    /// </summary>
    Object getNotificationUri() const;
    void setNotificationUri(Object const& value);
    /// <summary>
    /// 
    /// </summary>
    Object getExpiry() const;
    void setExpiry(Object const& value);
    bool expiryIsSet() const;
    void unsetExpiry();
    /// <summary>
    /// 
    /// </summary>
    Object getSupportedFeatures() const;
    void setSupportedFeatures(Object const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

    friend void to_json(nlohmann::json& j, const TrafficInfluSub& o);
    friend void from_json(const nlohmann::json& j, TrafficInfluSub& o);
protected:
    std::vector<Object> m_Dnns;
    bool m_DnnsIsSet;
    std::vector<Object> m_Snssais;
    bool m_SnssaisIsSet;
    std::vector<Object> m_InternalGroupIds;
    bool m_InternalGroupIdsIsSet;
    std::vector<Object> m_Supis;
    bool m_SupisIsSet;
    Object m_NotificationUri;

    Object m_Expiry;
    bool m_ExpiryIsSet;
    Object m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* TrafficInfluSub_H_ */
