/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpuData_2.h
 *
 * 
 */

#ifndef UpuData_2_H_
#define UpuData_2_H_


#include "Object.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UpuData_2
{
public:
    UpuData_2();
    virtual ~UpuData_2();

    void validate();

    /////////////////////////////////////////////
    /// UpuData_2 members

    /// <summary>
    /// 
    /// </summary>
    Object getSecPacket() const;
    void setSecPacket(Object const& value);
    bool secPacketIsSet() const;
    void unsetSecPacket();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Object>& getDefaultConfNssai();
    void setDefaultConfNssai(std::vector<Object> const& value);
    bool defaultConfNssaiIsSet() const;
    void unsetDefaultConfNssai();
    /// <summary>
    /// 
    /// </summary>
    Object getRoutingId() const;
    void setRoutingId(Object const& value);
    bool routingIdIsSet() const;
    void unsetRoutingId();

    friend void to_json(nlohmann::json& j, const UpuData_2& o);
    friend void from_json(const nlohmann::json& j, UpuData_2& o);
protected:
    Object m_SecPacket;
    bool m_SecPacketIsSet;
    std::vector<Object> m_DefaultConfNssai;
    bool m_DefaultConfNssaiIsSet;
    Object m_RoutingId;
    bool m_RoutingIdIsSet;
};

}
}
}
}

#endif /* UpuData_2_H_ */
