/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UsageThreshold.h
 *
 * 
 */

#ifndef UsageThreshold_H_
#define UsageThreshold_H_


#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UsageThreshold
{
public:
    UsageThreshold();
    virtual ~UsageThreshold();

    void validate();

    /////////////////////////////////////////////
    /// UsageThreshold members

    /// <summary>
    /// 
    /// </summary>
    Object getDuration() const;
    void setDuration(Object const& value);
    bool durationIsSet() const;
    void unsetDuration();
    /// <summary>
    /// 
    /// </summary>
    Object getTotalVolume() const;
    void setTotalVolume(Object const& value);
    bool totalVolumeIsSet() const;
    void unsetTotalVolume();
    /// <summary>
    /// 
    /// </summary>
    Object getDownlinkVolume() const;
    void setDownlinkVolume(Object const& value);
    bool downlinkVolumeIsSet() const;
    void unsetDownlinkVolume();
    /// <summary>
    /// 
    /// </summary>
    Object getUplinkVolume() const;
    void setUplinkVolume(Object const& value);
    bool uplinkVolumeIsSet() const;
    void unsetUplinkVolume();

    friend void to_json(nlohmann::json& j, const UsageThreshold& o);
    friend void from_json(const nlohmann::json& j, UsageThreshold& o);
protected:
    Object m_Duration;
    bool m_DurationIsSet;
    Object m_TotalVolume;
    bool m_TotalVolumeIsSet;
    Object m_DownlinkVolume;
    bool m_DownlinkVolumeIsSet;
    Object m_UplinkVolume;
    bool m_UplinkVolumeIsSet;
};

}
}
}
}

#endif /* UsageThreshold_H_ */
