/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Class5GVnGroupConfigurationDocumentApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

Class5GVnGroupConfigurationDocumentApiImpl::Class5GVnGroupConfigurationDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : Class5GVnGroupConfigurationDocumentApi(rtr)
    { }

void Class5GVnGroupConfigurationDocumentApiImpl::create5_g_vn_group(const std::string &externalGroupId, const 5GVnGroupConfiguration &r_5GVnGroupConfiguration, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

