/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* EventExposureGroupSubscriptionDocumentApiImpl.h
*
* 
*/

#ifndef EVENT_EXPOSURE_GROUP_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define EVENT_EXPOSURE_GROUP_SUBSCRIPTION_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <EventExposureGroupSubscriptionDocumentApi.h>

#include <pistache/optional.h>

#include "EeSubscription.h"
#include "Object.h"
#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class EventExposureGroupSubscriptionDocumentApiImpl : public org::openapitools::server::api::EventExposureGroupSubscriptionDocumentApi {
public:
    EventExposureGroupSubscriptionDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~EventExposureGroupSubscriptionDocumentApiImpl() {}

    void modify_ee_group_subscription(const std::string &ueGroupId, const std::string &subsId, const std::vector<PatchItem> &patchItem, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response);
    void query_ee_group_subscription(const std::string &ueGroupId, const std::string &subsId, Pistache::Http::ResponseWriter &response);
    void remove_ee_group_subscriptions(const std::string &ueGroupId, const std::string &subsId, Pistache::Http::ResponseWriter &response);
    void update_ee_group_subscriptions(const std::string &ueGroupId, const std::string &subsId, const EeSubscription &eeSubscription, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif