/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
*
* The version of the OpenAPI document: 2.1.2
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AuthenticationSubscriptionDocumentApiImpl.h"
#include "PatchResult.h"
#include "logger.hpp"

#include <AuthenticationSubscription.h>


namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

AuthenticationSubscriptionDocumentApiImpl::AuthenticationSubscriptionDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr,MYSQL *mysql)
    : AuthenticationSubscriptionDocumentApi(rtr)
    {
        mysql_WitcommUDRDB = mysql;
    }

void AuthenticationSubscriptionDocumentApiImpl::modify_authentication_subscription(const std::string &ueId, const std::vector<PatchItem> &patchItem, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) {

    MYSQL_RES *res = NULL;
    MYSQL_ROW row;
    const std::string select_Authenticationsubscription = "select * from AuthenticationSubscription WHERE ueid='"+ueId+"'";
    std::string query;
    nlohmann::json j,tmp_j;

    for(int i=0;i<patchItem.size();i++)
    {
        if((!strcmp(patchItem[i].getOp().c_str(), PATCH_OPERATION_REPLACE)) && patchItem[i].valueIsSet())
        {
            patchItem[i].getValue();
            SequenceNumber sequencenumber;
            nlohmann::json::parse(patchItem[i].getValue().c_str()).get_to(sequencenumber);

            if (mysql_real_query(mysql_WitcommUDRDB,select_Authenticationsubscription.c_str(), (unsigned long)select_Authenticationsubscription.size()))
            {
                Logger::udr_server().error("mysql_real_query failure！SQL(%s)",select_Authenticationsubscription);
                return;
            }

            res = mysql_store_result(mysql_WitcommUDRDB);
            if(res == NULL)
            {
                Logger::udr_server().error("mysql_store_result failure！SQL(%s)",select_Authenticationsubscription);
                return;
            }
            if (mysql_num_rows(res))
            {
                nlohmann::json sequencenumber_j;
                query="update AuthenticationSubscription set sequenceNumber='";

                to_json(sequencenumber_j,sequencenumber);
                query += sequencenumber_j.dump()+"'";
                query += " where ueid='"+ueId+"'";
            }
            else
            {
                Logger::udr_server().error("AuthenticationSubscription no data！");
            }

            mysql_free_result(res);

//            Logger::udr_server().debug("modify content: %s",query.c_str());
            if (mysql_real_query(mysql_WitcommUDRDB,query.c_str(), (unsigned long)query.size()))
            {
                Logger::udr_server().error("update mysql failure！");
                return;
            }
        }

        to_json(tmp_j,patchItem[i]);
        j+=tmp_j;
    }

    std::string out = j.dump();
    Logger::udr_server().debug("AuthenticationSubscription PATCH - json:\n\"%s\"",out.c_str());

    response.send(Pistache::Http::Code::No_Content, "");

}

void AuthenticationSubscriptionDocumentApiImpl::read_authentication_subscription(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response)
{
    MYSQL_RES *res = NULL;
    MYSQL_ROW row;
    MYSQL_FIELD* field = nullptr;

    nlohmann::json j;

    AuthenticationSubscription authenticationsubscription;
    const std::string query = "select * from AuthenticationSubscription WHERE ueid='"+ueId+"'";


    if (mysql_real_query(mysql_WitcommUDRDB,query.c_str(), (unsigned long)query.size()))
    {
        Logger::udr_server().error("mysql_real_query failure！");
        return;
    }

    res = mysql_store_result(mysql_WitcommUDRDB);
    if(res == NULL)
    {
        Logger::udr_server().error("mysql_store_result failure！");
        return;
    }

    row = mysql_fetch_row(res);

    if(row != NULL)
    {
        for (int i = 0; field = mysql_fetch_field(res); i++)
        {
            if(!strcmp("authenticationMethod", field->name))
            {
//                AuthMethod authenticationmethod;
//                nlohmann::json::parse(row[i]).get_to(authenticationmethod);
                authenticationsubscription.setAuthenticationMethod(row[i]);
            }
            else if(!strcmp("encPermanentKey", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setEncPermanentKey(row[i]);
            }
            else if(!strcmp("protectionParameterId", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setProtectionParameterId(row[i]);
            }
            else if(!strcmp("sequenceNumber", field->name) && row[i] != NULL)
            {
                SequenceNumber sequencenumber;
                nlohmann::json::parse(row[i]).get_to(sequencenumber);
                authenticationsubscription.setSequenceNumber(sequencenumber);
            }
            else if(!strcmp("authenticationManagementField", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setAuthenticationManagementField(row[i]);
            }
            else if(!strcmp("algorithmId", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setAlgorithmId(row[i]);
            }
            else if(!strcmp("encOpcKey", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setEncOpcKey(row[i]);
            }
            else if(!strcmp("encTopcKey", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setEncTopcKey(row[i]);
            }
            else if(!strcmp("vectorGenerationInHss", field->name) && row[i] != NULL)
            {
                std::cout<<row[i]<<std::endl;
                if(strcmp(row[i], "0"))
                    authenticationsubscription.setVectorGenerationInHss(true);
                else
                    authenticationsubscription.setVectorGenerationInHss(false);
            }
            else if(!strcmp("n5gcAuthMethod", field->name) && row[i] != NULL)
            {
//                AuthMethod n5gcauthmethod;
//                nlohmann::json::parse(row[i]).get_to(n5gcauthmethod);
                authenticationsubscription.setN5gcAuthMethod(row[i]);
            }
            else if(!strcmp("rgAuthenticationInd", field->name) && row[i] != NULL)
            {
                std::cout<<row[i]<<std::endl;
                if(strcmp(row[i], "0"))
                    authenticationsubscription.setRgAuthenticationInd(true);
                else
                    authenticationsubscription.setRgAuthenticationInd(false);
            }
            else if(!strcmp("supi", field->name) && row[i] != NULL)
            {
                authenticationsubscription.setSupi(row[i]);
            }
        }

        to_json(j,authenticationsubscription);
        response.send(Pistache::Http::Code::Ok, j.dump());

        std::string out = j.dump();
        Logger::udr_server().debug("AuthenticationSubscription GET - json:\n\"%s\"",out.c_str());
    }
    else
    {
        Logger::udr_server().error("AuthenticationSubscription no data！");
    }

    mysql_free_result(res);
}


}
}
}
}

