/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "IndividualBdtDataDocumentApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

IndividualBdtDataDocumentApiImpl::IndividualBdtDataDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : IndividualBdtDataDocumentApi(rtr)
    { }

void IndividualBdtDataDocumentApiImpl::create_individual_bdt_data(const std::string &bdtReferenceId, const BdtData &bdtData, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualBdtDataDocumentApiImpl::delete_individual_bdt_data(const std::string &bdtReferenceId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualBdtDataDocumentApiImpl::read_individual_bdt_data(const std::string &bdtReferenceId, const Pistache::Optional<std::string> &suppFeat, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualBdtDataDocumentApiImpl::update_individual_bdt_data(const std::string &bdtReferenceId, const BdtDataPatch &bdtDataPatch, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

