/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* IPTVConfigurationDataStoreApiImpl.h
*
* 
*/

#ifndef IPTV_CONFIGURATION_DATA_STORE_API_IMPL_H_
#define IPTV_CONFIGURATION_DATA_STORE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IPTVConfigurationDataStoreApi.h>

#include <pistache/optional.h>

#include "IptvConfigData.h"
#include "ProblemDetails.h"
#include "Snssai.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class IPTVConfigurationDataStoreApiImpl : public org::openapitools::server::api::IPTVConfigurationDataStoreApi {
public:
    IPTVConfigurationDataStoreApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~IPTVConfigurationDataStoreApiImpl() {}

    void read_iptv_congifuration_data(const Pistache::Optional<std::vector<std::string>> &configIds, const Pistache::Optional<std::vector<std::string>> &dnns, const Pistache::Optional<std::vector<Snssai>> &snssais, const Pistache::Optional<std::vector<std::string>> &supis, const Pistache::Optional<std::vector<std::string>> &interGroupIds, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif