/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* NSSAIUpdateAckDocumentApiImpl.h
*
* 
*/

#ifndef NSSAI_UPDATE_ACK_DOCUMENT_API_IMPL_H_
#define NSSAI_UPDATE_ACK_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <NSSAIUpdateAckDocumentApi.h>

#include <pistache/optional.h>

#include "NssaiAckData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class NSSAIUpdateAckDocumentApiImpl : public org::openapitools::server::api::NSSAIUpdateAckDocumentApi {
public:
    NSSAIUpdateAckDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~NSSAIUpdateAckDocumentApiImpl() {}

    void create_nssai_update_ack(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, const NssaiAckData &nssaiAckData, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif