/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "OperatorSpecificDataDocumentApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

OperatorSpecificDataDocumentApiImpl::OperatorSpecificDataDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : OperatorSpecificDataDocumentApi(rtr)
    { }

void OperatorSpecificDataDocumentApiImpl::read_operator_specific_data(const std::string &ueId, const Pistache::Optional<std::vector<std::string>> &fields, const Pistache::Optional<std::string> &suppFeat, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void OperatorSpecificDataDocumentApiImpl::replace_operator_specific_data(const std::string &ueId, const std::map<std::string, OperatorSpecificDataContainer> &requestBody, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void OperatorSpecificDataDocumentApiImpl::update_operator_specific_data(const std::string &ueId, const std::vector<PatchItem> &patchItem, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

