/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Query5GVnGroupConfigurationDocumentApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

Query5GVnGroupConfigurationDocumentApiImpl::Query5GVnGroupConfigurationDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : Query5GVnGroupConfigurationDocumentApi(rtr)
    { }

void Query5GVnGroupConfigurationDocumentApiImpl::get5_g_vn_group_configuration(const std::string &externalGroupId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

