/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl.h
*
* 
*/

#ifndef QUERY_NIDD_AUTHORIZATION_DATA_GPSI_OR_EXTERNAL_GROUP_IDENTIFIER_DOCUMENT_API_IMPL_H_
#define QUERY_NIDD_AUTHORIZATION_DATA_GPSI_OR_EXTERNAL_GROUP_IDENTIFIER_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApi.h>

#include <pistache/optional.h>

#include "AuthorizationData.h"
#include "Snssai.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl : public org::openapitools::server::api::QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApi {
public:
    QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl() {}

    void get_nidd_au_data(const std::string &ueId, const Pistache::Optional<Snssai> &singleNssai, const Pistache::Optional<std::string> &dnn, const Pistache::Optional<std::string> &mtcProviderInformation, const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch, const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif