/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AppDescriptor.h
 *
 * 
 */

#ifndef AppDescriptor_H_
#define AppDescriptor_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AppDescriptor
{
public:
    AppDescriptor();
    virtual ~AppDescriptor();

    void validate();

    /////////////////////////////////////////////
    /// AppDescriptor members

    /// <summary>
    /// 
    /// </summary>
    std::string getOsId() const;
    void setOsId(std::string const& value);
    bool osIdIsSet() const;
    void unsetOsId();
    /// <summary>
    /// 
    /// </summary>
    std::string getAppId() const;
    void setAppId(std::string const& value);
    bool appIdIsSet() const;
    void unsetAppId();

    friend void to_json(nlohmann::json& j, const AppDescriptor& o);
    friend void from_json(const nlohmann::json& j, AppDescriptor& o);
protected:
    std::string m_OsId;
    bool m_OsIdIsSet;
    std::string m_AppId;
    bool m_AppIdIsSet;
};

}
}
}
}

#endif /* AppDescriptor_H_ */
