/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ApplicationDataChangeNotif.h
 *
 * Contains changed application data for which notification was requested.
 */

#ifndef ApplicationDataChangeNotif_H_
#define ApplicationDataChangeNotif_H_


#include "IptvConfigData.h"
#include "ServiceParameterData.h"
#include "PfdChangeNotification.h"
#include "BdtPolicyData.h"
#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains changed application data for which notification was requested.
/// </summary>
class  ApplicationDataChangeNotif
{
public:
    ApplicationDataChangeNotif();
    virtual ~ApplicationDataChangeNotif();

    void validate();

    /////////////////////////////////////////////
    /// ApplicationDataChangeNotif members

    /// <summary>
    /// 
    /// </summary>
    IptvConfigData getIptvConfigData() const;
    void setIptvConfigData(IptvConfigData const& value);
    bool iptvConfigDataIsSet() const;
    void unsetIptvConfigData();
    /// <summary>
    /// 
    /// </summary>
    PfdChangeNotification getPfdData() const;
    void setPfdData(PfdChangeNotification const& value);
    bool pfdDataIsSet() const;
    void unsetPfdData();
    /// <summary>
    /// 
    /// </summary>
    BdtPolicyData getBdtPolicyData() const;
    void setBdtPolicyData(BdtPolicyData const& value);
    bool bdtPolicyDataIsSet() const;
    void unsetBdtPolicyData();
    /// <summary>
    /// 
    /// </summary>
    std::string getResUri() const;
    void setResUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    ServiceParameterData getSerParamData() const;
    void setSerParamData(ServiceParameterData const& value);
    bool serParamDataIsSet() const;
    void unsetSerParamData();

    friend void to_json(nlohmann::json& j, const ApplicationDataChangeNotif& o);
    friend void from_json(const nlohmann::json& j, ApplicationDataChangeNotif& o);
protected:
    IptvConfigData m_IptvConfigData;
    bool m_IptvConfigDataIsSet;
    PfdChangeNotification m_PfdData;
    bool m_PfdDataIsSet;
    BdtPolicyData m_BdtPolicyData;
    bool m_BdtPolicyDataIsSet;
    std::string m_ResUri;

    ServiceParameterData m_SerParamData;
    bool m_SerParamDataIsSet;
};

}
}
}
}

#endif /* ApplicationDataChangeNotif_H_ */
