/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ApplicationDataSubs.h
 *
 * Identifies a subscription to application data change notification.
 */

#ifndef ApplicationDataSubs_H_
#define ApplicationDataSubs_H_


#include <string>
#include "DataFilter.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Identifies a subscription to application data change notification.
/// </summary>
class  ApplicationDataSubs
{
public:
    ApplicationDataSubs();
    virtual ~ApplicationDataSubs();

    void validate();

    /////////////////////////////////////////////
    /// ApplicationDataSubs members

    /// <summary>
    /// 
    /// </summary>
    std::string getNotificationUri() const;
    void setNotificationUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<DataFilter>& getDataFilters();
    void setDataFilters(std::vector<DataFilter> const& value);
    bool dataFiltersIsSet() const;
    void unsetDataFilters();
    /// <summary>
    /// 
    /// </summary>
    std::string getExpiry() const;
    void setExpiry(std::string const& value);
    bool expiryIsSet() const;
    void unsetExpiry();
    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

    friend void to_json(nlohmann::json& j, const ApplicationDataSubs& o);
    friend void from_json(const nlohmann::json& j, ApplicationDataSubs& o);
protected:
    std::string m_NotificationUri;

    std::vector<DataFilter> m_DataFilters;
    bool m_DataFiltersIsSet;
    std::string m_Expiry;
    bool m_ExpiryIsSet;
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* ApplicationDataSubs_H_ */
