/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Area.h
 *
 * 
 */

#ifndef Area_H_
#define Area_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Area
{
public:
    Area();
    virtual ~Area();

    void validate();

    /////////////////////////////////////////////
    /// Area members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getTacs();
    void setTacs(std::vector<std::string> const& value);
    bool tacsIsSet() const;
    void unsetTacs();
    /// <summary>
    /// 
    /// </summary>
    std::string getAreaCode() const;
    void setAreaCode(std::string const& value);
    bool areaCodeIsSet() const;
    void unsetAreaCode();

    friend void to_json(nlohmann::json& j, const Area& o);
    friend void from_json(const nlohmann::json& j, Area& o);
protected:
    std::vector<std::string> m_Tacs;
    bool m_TacsIsSet;
    std::string m_AreaCode;
    bool m_AreaCodeIsSet;
};

}
}
}
}

#endif /* Area_H_ */
