/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AuthorizationData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

AuthorizationData::AuthorizationData() {
  m_ValidityTime = "";
  m_ValidityTimeIsSet = false;
}

AuthorizationData::~AuthorizationData() {}

void AuthorizationData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const AuthorizationData &o) {
  j = nlohmann::json();
  //    j["authorizationData"] = o.m_AuthorizationData;
  if (o.validityTimeIsSet())
    j["validityTime"] = o.m_ValidityTime;
}

void from_json(const nlohmann::json &j, AuthorizationData &o) {
  //    j.at("authorizationData").get_to(o.m_AuthorizationData);
  if (j.find("validityTime") != j.end()) {
    j.at("validityTime").get_to(o.m_ValidityTime);
    o.m_ValidityTimeIsSet = true;
  }
}

// Set<UserIdentifier>& AuthorizationData::getAuthorizationData()
//{
//    return m_AuthorizationData;
//}
// void AuthorizationData::setAuthorizationData(Set<UserIdentifier> const&
// value)
//{
//    m_AuthorizationData = value;
//}
std::string AuthorizationData::getValidityTime() const {
  return m_ValidityTime;
}
void AuthorizationData::setValidityTime(std::string const &value) {
  m_ValidityTime = value;
  m_ValidityTimeIsSet = true;
}
bool AuthorizationData::validityTimeIsSet() const {
  return m_ValidityTimeIsSet;
}
void AuthorizationData::unsetValidityTime() { m_ValidityTimeIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
