/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CmState.h
 *
 * 
 */

#ifndef CmState_H_
#define CmState_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CmState
{
public:
    CmState();
    virtual ~CmState();

    void validate();

    /////////////////////////////////////////////
    /// CmState members


    friend void to_json(nlohmann::json& j, const CmState& o);
    friend void from_json(const nlohmann::json& j, CmState& o);
protected:
};

}
}
}
}

#endif /* CmState_H_ */
