/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContextInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ContextInfo::ContextInfo() { m_OrigHeadersIsSet = false; }

ContextInfo::~ContextInfo() {}

void ContextInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const ContextInfo &o) {
  j = nlohmann::json();
  if (o.origHeadersIsSet() || !o.m_OrigHeaders.empty())
    j["origHeaders"] = o.m_OrigHeaders;
}

void from_json(const nlohmann::json &j, ContextInfo &o) {
  if (j.find("origHeaders") != j.end()) {
    j.at("origHeaders").get_to(o.m_OrigHeaders);
    o.m_OrigHeadersIsSet = true;
  }
}

std::vector<std::string> &ContextInfo::getOrigHeaders() {
  return m_OrigHeaders;
}
void ContextInfo::setOrigHeaders(std::vector<std::string> const &value) {
  m_OrigHeaders = value;
  m_OrigHeadersIsSet = true;
}
bool ContextInfo::origHeadersIsSet() const { return m_OrigHeadersIsSet; }
void ContextInfo::unsetOrigHeaders() { m_OrigHeadersIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
