/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Ecgi.h
 *
 * 
 */

#ifndef Ecgi_H_
#define Ecgi_H_


#include <string>
#include "PlmnId.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Ecgi
{
public:
    Ecgi();
    virtual ~Ecgi();

    void validate();

    /////////////////////////////////////////////
    /// Ecgi members

    /// <summary>
    /// 
    /// </summary>
    PlmnId getPlmnId() const;
    void setPlmnId(PlmnId const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getEutraCellId() const;
    void setEutraCellId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getNid() const;
    void setNid(std::string const& value);
    bool nidIsSet() const;
    void unsetNid();

    friend void to_json(nlohmann::json& j, const Ecgi& o);
    friend void from_json(const nlohmann::json& j, Ecgi& o);
protected:
    PlmnId m_PlmnId;

    std::string m_EutraCellId;

    std::string m_Nid;
    bool m_NidIsSet;
};

}
}
}
}

#endif /* Ecgi_H_ */
