/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ExposureDataSubscription.h
 *
 * 
 */

#ifndef ExposureDataSubscription_H_
#define ExposureDataSubscription_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ExposureDataSubscription
{
public:
    ExposureDataSubscription();
    virtual ~ExposureDataSubscription();

    void validate();

    /////////////////////////////////////////////
    /// ExposureDataSubscription members

    /// <summary>
    /// 
    /// </summary>
    std::string getNotificationUri() const;
    void setNotificationUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getMonitoredResourceUris();
    void setMonitoredResourceUris(std::vector<std::string> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getExpiry() const;
    void setExpiry(std::string const& value);
    bool expiryIsSet() const;
    void unsetExpiry();
    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

    friend void to_json(nlohmann::json& j, const ExposureDataSubscription& o);
    friend void from_json(const nlohmann::json& j, ExposureDataSubscription& o);
protected:
    std::string m_NotificationUri;

    std::vector<std::string> m_MonitoredResourceUris;

    std::string m_Expiry;
    bool m_ExpiryIsSet;
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* ExposureDataSubscription_H_ */
