/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "GeographicalCoordinates.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

GeographicalCoordinates::GeographicalCoordinates()
{
    m_Lon = 0.0;
    m_Lat = 0.0;
    
}

GeographicalCoordinates::~GeographicalCoordinates()
{
}

void GeographicalCoordinates::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const GeographicalCoordinates& o)
{
    j = nlohmann::json();
    j["lon"] = o.m_Lon;
    j["lat"] = o.m_Lat;
}

void from_json(const nlohmann::json& j, GeographicalCoordinates& o)
{
    j.at("lon").get_to(o.m_Lon);
    j.at("lat").get_to(o.m_Lat);
}

double GeographicalCoordinates::getLon() const
{
    return m_Lon;
}
void GeographicalCoordinates::setLon(double const value)
{
    m_Lon = value;
}
double GeographicalCoordinates::getLat() const
{
    return m_Lat;
}
void GeographicalCoordinates::setLat(double const value)
{
    m_Lat = value;
}

}
}
}
}

