/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Ipv6Addr.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Ipv6Addr::Ipv6Addr() {}

Ipv6Addr::~Ipv6Addr() {}

void Ipv6Addr::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const Ipv6Addr &o) { j = nlohmann::json(); }

void from_json(const nlohmann::json &j, Ipv6Addr &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
