/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LcsMoData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

LcsMoData::LcsMoData() {}

LcsMoData::~LcsMoData() {}

void LcsMoData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const LcsMoData &o) {
  j = nlohmann::json();
  j["allowedServiceClasses"] = o.m_AllowedServiceClasses;
}

void from_json(const nlohmann::json &j, LcsMoData &o) {
  j.at("allowedServiceClasses").get_to(o.m_AllowedServiceClasses);
}

std::vector<LcsMoServiceClass> &LcsMoData::getAllowedServiceClasses() {
  return m_AllowedServiceClasses;
}
void LcsMoData::setAllowedServiceClasses(
    std::vector<LcsMoServiceClass> const &value) {
  m_AllowedServiceClasses = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
