/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OdbPacketServices.h
 *
 * 
 */

#ifndef OdbPacketServices_H_
#define OdbPacketServices_H_


#include "NullValue.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  OdbPacketServices
{
public:
    OdbPacketServices();
    virtual ~OdbPacketServices();

    void validate();

    /////////////////////////////////////////////
    /// OdbPacketServices members


    friend void to_json(nlohmann::json& j, const OdbPacketServices& o);
    friend void from_json(const nlohmann::json& j, OdbPacketServices& o);
protected:
};

}
}
}
}

#endif /* OdbPacketServices_H_ */
