/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PatchResult.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PatchResult::PatchResult() {}

PatchResult::~PatchResult() {}

void PatchResult::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const PatchResult &o) {
  j = nlohmann::json();
  j["report"] = o.m_Report;
}

void from_json(const nlohmann::json &j, PatchResult &o) {
  j.at("report").get_to(o.m_Report);
}

std::vector<ReportItem> &PatchResult::getReport() { return m_Report; }
void PatchResult::setReport(std::vector<ReportItem> const &value) {
  m_Report = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
