/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
*
* The version of the OpenAPI document: 2.1.2
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PatchItem.h
 *
 *
 */

#ifndef PatchItem_H_
#define PatchItem_H_


#include <string>
#include "PatchOperation.h"
//#include "AnyType.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class  PatchItem
{
public:
    PatchItem();
    virtual ~PatchItem();

    void validate();

    /////////////////////////////////////////////
    /// PatchItem members

    /// <summary>
    ///
    /// </summary>
    PatchOperation getOp() const;
    void setOp(PatchOperation const& value);
    /// <summary>
    ///
    /// </summary>
    std::string getPath() const;
    void setPath(std::string const& value);
    /// <summary>
    ///
    /// </summary>
    std::string getFrom() const;
    void setFrom(std::string const& value);
    bool fromIsSet() const;
    void unsetFrom();
    /// <summary>
    ///
    /// </summary>
    std::string getValue() const;
    void setValue(std::string const& value);
    bool valueIsSet() const;
    void unsetValue();

    friend void to_json(nlohmann::json& j, const PatchItem& o);
    friend void from_json(const nlohmann::json& j, PatchItem& o);
protected:
    PatchOperation m_Op;

    std::string m_Path;

    std::string m_From;
    bool m_FromIsSet;
    std::string m_Value;
    bool m_ValueIsSet;
};

}
}
}
}

#endif /* PatchItem_H_ */
