/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PduSessionStatus.h
 *
 * Possible values are - \&quot;ACTIVE\&quot; - \&quot;RELEASED\&quot; 
 */

#ifndef PduSessionStatus_H_
#define PduSessionStatus_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are - \&quot;ACTIVE\&quot; - \&quot;RELEASED\&quot; 
/// </summary>
class  PduSessionStatus
{
public:
    PduSessionStatus();
    virtual ~PduSessionStatus();

    void validate();

    /////////////////////////////////////////////
    /// PduSessionStatus members


    friend void to_json(nlohmann::json& j, const PduSessionStatus& o);
    friend void from_json(const nlohmann::json& j, PduSessionStatus& o);
protected:
};

}
}
}
}

#endif /* PduSessionStatus_H_ */
