/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnIdNid.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PlmnIdNid::PlmnIdNid()
{
    m_Mcc = "";
    m_Mnc = "";
    m_Nid = "";
    m_NidIsSet = false;
    
}

PlmnIdNid::~PlmnIdNid()
{
}

void PlmnIdNid::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const PlmnIdNid& o)
{
    j = nlohmann::json();
    j["mcc"] = o.m_Mcc;
    j["mnc"] = o.m_Mnc;
    if(o.nidIsSet())
        j["nid"] = o.m_Nid;
}

void from_json(const nlohmann::json& j, PlmnIdNid& o)
{
    j.at("mcc").get_to(o.m_Mcc);
    j.at("mnc").get_to(o.m_Mnc);
    if(j.find("nid") != j.end())
    {
        j.at("nid").get_to(o.m_Nid);
        o.m_NidIsSet = true;
    } 
}

std::string PlmnIdNid::getMcc() const
{
    return m_Mcc;
}
void PlmnIdNid::setMcc(std::string const& value)
{
    m_Mcc = value;
}
std::string PlmnIdNid::getMnc() const
{
    return m_Mnc;
}
void PlmnIdNid::setMnc(std::string const& value)
{
    m_Mnc = value;
}
std::string PlmnIdNid::getNid() const
{
    return m_Nid;
}
void PlmnIdNid::setNid(std::string const& value)
{
    m_Nid = value;
    m_NidIsSet = true;
}
bool PlmnIdNid::nidIsSet() const
{
    return m_NidIsSet;
}
void PlmnIdNid::unsetNid()
{
    m_NidIsSet = false;
}

}
}
}
}

