/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PointUncertaintyEllipse.h
 *
 * 
 */

#ifndef PointUncertaintyEllipse_H_
#define PointUncertaintyEllipse_H_


#include "GeographicalCoordinates.h"
#include "UncertaintyEllipse.h"
#include "GADShape.h"
#include "PointUncertaintyEllipse_allOf.h"
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PointUncertaintyEllipse
{
public:
    PointUncertaintyEllipse();
    virtual ~PointUncertaintyEllipse();

    void validate();

    /////////////////////////////////////////////
    /// PointUncertaintyEllipse members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
    /// <summary>
    /// 
    /// </summary>
    GeographicalCoordinates getPoint() const;
    void setPoint(GeographicalCoordinates const& value);
    /// <summary>
    /// 
    /// </summary>
    UncertaintyEllipse getUncertaintyEllipse() const;
    void setUncertaintyEllipse(UncertaintyEllipse const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getConfidence() const;
    void setConfidence(int32_t const value);

    friend void to_json(nlohmann::json& j, const PointUncertaintyEllipse& o);
    friend void from_json(const nlohmann::json& j, PointUncertaintyEllipse& o);
protected:
    SupportedGADShapes m_Shape;

    GeographicalCoordinates m_Point;

    UncertaintyEllipse m_UncertaintyEllipse;

    int32_t m_Confidence;

};

}
}
}
}

#endif /* PointUncertaintyEllipse_H_ */
