/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PpDlPacketCountExt.h
 *
 * 
 */

#ifndef PpDlPacketCountExt_H_
#define PpDlPacketCountExt_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PpDlPacketCountExt
{
public:
    PpDlPacketCountExt();
    virtual ~PpDlPacketCountExt();

    void validate();

    /////////////////////////////////////////////
    /// PpDlPacketCountExt members

    /// <summary>
    /// 
    /// </summary>
    std::string getAfInstanceId() const;
    void setAfInstanceId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getReferenceId() const;
    void setReferenceId(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    std::string getValidityTime() const;
    void setValidityTime(std::string const& value);
    bool validityTimeIsSet() const;
    void unsetValidityTime();
    /// <summary>
    /// 
    /// </summary>
    std::string getMtcProviderInformation() const;
    void setMtcProviderInformation(std::string const& value);
    bool mtcProviderInformationIsSet() const;
    void unsetMtcProviderInformation();

    friend void to_json(nlohmann::json& j, const PpDlPacketCountExt& o);
    friend void from_json(const nlohmann::json& j, PpDlPacketCountExt& o);
protected:
    std::string m_AfInstanceId;

    int32_t m_ReferenceId;

    std::string m_ValidityTime;
    bool m_ValidityTimeIsSet;
    std::string m_MtcProviderInformation;
    bool m_MtcProviderInformationIsSet;
};

}
}
}
}

#endif /* PpDlPacketCountExt_H_ */
