/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RmInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RmInfo::RmInfo()
{
    
}

RmInfo::~RmInfo()
{
}

void RmInfo::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const RmInfo& o)
{
    j = nlohmann::json();
    j["rmState"] = o.m_RmState;
    j["accessType"] = o.m_AccessType;
}

void from_json(const nlohmann::json& j, RmInfo& o)
{
    j.at("rmState").get_to(o.m_RmState);
    j.at("accessType").get_to(o.m_AccessType);
}

RmState RmInfo::getRmState() const
{
    return m_RmState;
}
void RmInfo::setRmState(RmState const& value)
{
    m_RmState = value;
}
AccessType RmInfo::getAccessType() const
{
    return m_AccessType;
}
void RmInfo::setAccessType(AccessType const& value)
{
    m_AccessType = value;
}

}
}
}
}

