/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TrafficInfluDataNotif.h
 *
 * 
 */

#ifndef TrafficInfluDataNotif_H_
#define TrafficInfluDataNotif_H_


#include "TrafficInfluData.h"
#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  TrafficInfluDataNotif
{
public:
    TrafficInfluDataNotif();
    virtual ~TrafficInfluDataNotif();

    void validate();

    /////////////////////////////////////////////
    /// TrafficInfluDataNotif members

    /// <summary>
    /// 
    /// </summary>
    std::string getResUri() const;
    void setResUri(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    TrafficInfluData getTrafficInfluData() const;
    void setTrafficInfluData(TrafficInfluData const& value);
    bool trafficInfluDataIsSet() const;
    void unsetTrafficInfluData();

    friend void to_json(nlohmann::json& j, const TrafficInfluDataNotif& o);
    friend void from_json(const nlohmann::json& j, TrafficInfluDataNotif& o);
protected:
    std::string m_ResUri;

    TrafficInfluData m_TrafficInfluData;
    bool m_TrafficInfluDataIsSet;
};

}
}
}
}

#endif /* TrafficInfluDataNotif_H_ */
