/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpdatedItem.h
 *
 * Identifies a fragment of a resource.
 */

#ifndef UpdatedItem_H_
#define UpdatedItem_H_


#include <string>
//#include "AnyType.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Identifies a fragment of a resource.
/// </summary>
class  UpdatedItem
{
public:
    UpdatedItem();
    virtual ~UpdatedItem();

    void validate();

    /////////////////////////////////////////////
    /// UpdatedItem members

    /// <summary>
    /// Identifies a fragment (subset of resource data) of a given resource.
    /// </summary>
    std::string getItem() const;
    void setItem(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
//    AnyType getValue() const;
//    void setValue(AnyType const& value);

    friend void to_json(nlohmann::json& j, const UpdatedItem& o);
    friend void from_json(const nlohmann::json& j, UpdatedItem& o);
protected:
    std::string m_Item;

//    AnyType m_Value;

};

}
}
}
}

#endif /* UpdatedItem_H_ */
