/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UpSecurity.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UpSecurity::UpSecurity() {}

UpSecurity::~UpSecurity() {}

void UpSecurity::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const UpSecurity &o) {
  j = nlohmann::json();
  j["upIntegr"] = o.m_UpIntegr;
  j["upConfid"] = o.m_UpConfid;
}

void from_json(const nlohmann::json &j, UpSecurity &o) {
  j.at("upIntegr").get_to(o.m_UpIntegr);
  j.at("upConfid").get_to(o.m_UpConfid);
}

UpIntegrity UpSecurity::getUpIntegr() const { return m_UpIntegr; }
void UpSecurity::setUpIntegr(UpIntegrity const &value) { m_UpIntegr = value; }
UpConfidentiality UpSecurity::getUpConfid() const { return m_UpConfid; }
void UpSecurity::setUpConfid(UpConfidentiality const &value) {
  m_UpConfid = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
