/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * WirelineArea.h
 *
 * 
 */

#ifndef WirelineArea_H_
#define WirelineArea_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  WirelineArea
{
public:
    WirelineArea();
    virtual ~WirelineArea();

    void validate();

    /////////////////////////////////////////////
    /// WirelineArea members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getGlobalLineIds();
    void setGlobalLineIds(std::vector<std::string> const& value);
    bool globalLineIdsIsSet() const;
    void unsetGlobalLineIds();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getHfcNIds();
    void setHfcNIds(std::vector<std::string> const& value);
    bool hfcNIdsIsSet() const;
    void unsetHfcNIds();
    /// <summary>
    /// 
    /// </summary>
    std::string getAreaCodeB() const;
    void setAreaCodeB(std::string const& value);
    bool areaCodeBIsSet() const;
    void unsetAreaCodeB();
    /// <summary>
    /// 
    /// </summary>
    std::string getAreaCodeC() const;
    void setAreaCodeC(std::string const& value);
    bool areaCodeCIsSet() const;
    void unsetAreaCodeC();

    friend void to_json(nlohmann::json& j, const WirelineArea& o);
    friend void from_json(const nlohmann::json& j, WirelineArea& o);
protected:
    std::vector<std::string> m_GlobalLineIds;
    bool m_GlobalLineIdsIsSet;
    std::vector<std::string> m_HfcNIds;
    bool m_HfcNIdsIsSet;
    std::string m_AreaCodeB;
    bool m_AreaCodeBIsSet;
    std::string m_AreaCodeC;
    bool m_AreaCodeCIsSet;
};

}
}
}
}

#endif /* WirelineArea_H_ */
