/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AccessAndMobilityPolicyDataDocumentApiImpl.h"

#include "logger.hpp"
#include "udr_app.hpp"
#include "udr_config.hpp"
using namespace config;
extern config::udr_config udr_cfg;
namespace oai::udr::api {

using namespace oai::udr::model;

AccessAndMobilityPolicyDataDocumentApiImpl::
    AccessAndMobilityPolicyDataDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr, udr_app *udr_app_inst,
        std::string address)
    : AccessAndMobilityPolicyDataDocumentApi(rtr),
      m_udr_app(udr_app_inst),
      m_address(address) {}

void AccessAndMobilityPolicyDataDocumentApiImpl::
    read_access_and_mobility_policy_data(
        const std::string &ueId, Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace oai::udr::api
