/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * AmfSubscriptionInfoDocumentApiImpl.h
 *
 *
 */

#ifndef _AMF_SUBSCRIPTION_INFO_DOCUMENT_API_IMPL_H_
#define _AMF_SUBSCRIPTION_INFO_DOCUMENT_API_IMPL_H_

#include "PatchItem.h"
#include "udr_app.hpp"
#include <AmfSubscriptionInfoDocumentApi.h>
#include <pistache/http.h>
#include <vector>

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class AmfSubscriptionInfoDocumentApiImpl
    : public oai::udr::api::AmfSubscriptionInfoDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  AmfSubscriptionInfoDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~AmfSubscriptionInfoDocumentApiImpl() {}

  void modify_amf_subscription_info(
      const std::string& ueId, const std::string& subsId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
