/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ContextDataDocumentApiImpl.h
 *
 *
 */

#ifndef CONTEXT_DATA_DOCUMENT_API_IMPL_H_
#define CONTEXT_DATA_DOCUMENT_API_IMPL_H_

#include <ContextDataDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "ContextDataSetName.h"
#include "ContextDataSets.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class ContextDataDocumentApiImpl
    : public oai::udr::api::ContextDataDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  ContextDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~ContextDataDocumentApiImpl() {}

  //    void query_context_data(const std::string &ueId, const
  //    Pistache::Optional<Set<ContextDataSetName>> &contextDatasetNames,
  //    Pistache::Http::ResponseWriter &response);
};

}  // namespace oai::udr::api

#endif
