/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContextDataDocumentApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ContextDataDocumentApiImpl::ContextDataDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr)
    : ContextDataDocumentApi(rtr) {}

// void ContextDataDocumentApiImpl::query_context_data(const std::string &ueId,
// const Pistache::Optional<Set<ContextDataSetName>> &contextDatasetNames,
// Pistache::Http::ResponseWriter &response) {
//    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
//}

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org
