/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Delete5GVnGroupApiImpl.h
 *
 *
 */

#ifndef DELETE5_G_VN_GROUP_API_IMPL_H_
#define DELETE5_G_VN_GROUP_API_IMPL_H_

#include <Delete5GVnGroupApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "udr_app.hpp"

using namespace oai::udr::app;
namespace oai::udr::api {

class Delete5GVnGroupApiImpl : public oai::udr::api::Delete5GVnGroupApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  Delete5GVnGroupApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~Delete5GVnGroupApiImpl() {}

  void delete5_g_vn_group(
      const std::string& externalGroupId,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
