/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * GroupIdentifiersApiImpl.h
 *
 *
 */

#ifndef GROUP_IDENTIFIERS_API_IMPL_H_
#define GROUP_IDENTIFIERS_API_IMPL_H_

#include <GroupIdentifiersApi.h>
#include <pistache/http.h>
#include <optional>

#include "GroupIdentifiers.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::_3gpp::model;
using namespace oai::udr::app;

class GroupIdentifiersApiImpl : public oai::udr::api::GroupIdentifiersApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  GroupIdentifiersApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~GroupIdentifiersApiImpl() {}

  void get_group_identifiers(
      const std::optional<std::string>& extGroupId,
      const std::optional<std::string>& intGroupId,
      const std::optional<bool>& ueIdInd,
      const std::optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
