/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualApplicationDataSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_APPLICATION_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_APPLICATION_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <IndividualApplicationDataSubscriptionDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "ApplicationDataSubs.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class IndividualApplicationDataSubscriptionDocumentApiImpl
    : public oai::udr::api::IndividualApplicationDataSubscriptionDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  IndividualApplicationDataSubscriptionDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~IndividualApplicationDataSubscriptionDocumentApiImpl() {}

  void delete_individual_application_data_subscription(
      const std::string& subsId, Pistache::Http::ResponseWriter& response);
  void read_individual_application_data_subscription(
      const std::string& subsId, Pistache::Http::ResponseWriter& response);
  void replace_individual_application_data_subscription(
      const std::string& subsId, const ApplicationDataSubs& applicationDataSubs,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
