/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualBdtDataDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_BDT_DATA_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_BDT_DATA_DOCUMENT_API_IMPL_H_

#include <IndividualBdtDataDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "BdtData.h"
#include "BdtDataPatch.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class IndividualBdtDataDocumentApiImpl
    : public oai::udr::api::IndividualBdtDataDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  IndividualBdtDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~IndividualBdtDataDocumentApiImpl() {}

  void create_individual_bdt_data(
      const std::string& bdtReferenceId, const BdtData& bdtData,
      Pistache::Http::ResponseWriter& response);
  void delete_individual_bdt_data(
      const std::string& bdtReferenceId,
      Pistache::Http::ResponseWriter& response);
  void read_individual_bdt_data(
      const std::string& bdtReferenceId,
      const Pistache::Optional<std::string>& suppFeat,
      Pistache::Http::ResponseWriter& response);
  void update_individual_bdt_data(
      const std::string& bdtReferenceId, const BdtDataPatch& bdtDataPatch,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
