/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualAppliedBDTPolicyDataDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_APPLIED_BDT_POLICY_DATA_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_APPLIED_BDT_POLICY_DATA_DOCUMENT_API_IMPL_H_

#include <IndividualAppliedBDTPolicyDataDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "BdtPolicyData.h"
#include "BdtPolicyDataPatch.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class IndividualAppliedBDTPolicyDataDocumentApiImpl
    : public oai::udr::api::IndividualAppliedBDTPolicyDataDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  IndividualAppliedBDTPolicyDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~IndividualAppliedBDTPolicyDataDocumentApiImpl() {}

  void delete_individual_applied_bdt_policy_data(
      const std::string& bdtPolicyId, Pistache::Http::ResponseWriter& response);
  void update_individual_applied_bdt_policy_data(
      const std::string& bdtPolicyId,
      const BdtPolicyDataPatch& bdtPolicyDataPatch,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
