/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* IndividualBDTPolicyDataDocumentApiImpl.h
*
* 
*/

#ifndef INDIVIDUAL_BDT_POLICY_DATA_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_BDT_POLICY_DATA_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualBDTPolicyDataDocumentApi.h>

#include <pistache/optional.h>

#include "BdtPolicyData.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::udr::api {

using namespace oai::udr::model;

class IndividualBDTPolicyDataDocumentApiImpl : public oai::udr::api::IndividualBDTPolicyDataDocumentApi {
public:
    IndividualBDTPolicyDataDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~IndividualBDTPolicyDataDocumentApiImpl() {}

    void create_individual_applied_bdt_policy_data(const std::string &bdtPolicyId, const BdtPolicyData &bdtPolicyData, Pistache::Http::ResponseWriter &response);

};

}






#endif