/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualInfluenceDataSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_INFLUENCE_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_INFLUENCE_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <IndividualInfluenceDataSubscriptionDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "TrafficInfluSub.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class IndividualInfluenceDataSubscriptionDocumentApiImpl
    : public oai::udr::api::IndividualInfluenceDataSubscriptionDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  IndividualInfluenceDataSubscriptionDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~IndividualInfluenceDataSubscriptionDocumentApiImpl() {}

  void delete_individual_influence_data_subscription(
      const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
  void read_individual_influence_data_subscription(
      const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
  void replace_individual_influence_data_subscription(
      const std::string& subscriptionId, const TrafficInfluSub& trafficInfluSub,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
