/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IndividualExposureDataSubscriptionDocumentApiImpl.h"

namespace oai::udr::api {

using namespace oai::udr::model;

IndividualExposureDataSubscriptionDocumentApiImpl::
    IndividualExposureDataSubscriptionDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr)
    : IndividualExposureDataSubscriptionDocumentApi(rtr) {}

void IndividualExposureDataSubscriptionDocumentApiImpl::
    delete_individual_exposure_data_subscription(
        const std::string &subId, Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualExposureDataSubscriptionDocumentApiImpl::
    replace_individual_exposure_data_subscription(
        const std::string &subId,
        const ExposureDataSubscription &exposureDataSubscription,
        Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace oai::udr::model
