/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* IndividualIPTVConfigurationDataApiImpl.h
*
* 
*/

#ifndef INDIVIDUAL_IPTV_CONFIGURATION_DATA_API_IMPL_H_
#define INDIVIDUAL_IPTV_CONFIGURATION_DATA_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualIPTVConfigurationDataApi.h>

#include <pistache/optional.h>

#include "IptvConfigData.h"
#include "IptvConfigDataPatch.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::udr::api {

using namespace oai::udr::model;

class IndividualIPTVConfigurationDataApiImpl : public oai::udr::api::IndividualIPTVConfigurationDataApi {
public:
    IndividualIPTVConfigurationDataApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~IndividualIPTVConfigurationDataApiImpl() {}

    void partial_replace_individual_iptv_configuration_data(const std::string &configurationId, const IptvConfigDataPatch &iptvConfigDataPatch, Pistache::Http::ResponseWriter &response);

};

}






#endif