/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualIPTVConfigurationDataApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_IPTV_CONFIGURATION_DATA_API_IMPL_H_
#define INDIVIDUAL_IPTV_CONFIGURATION_DATA_API_IMPL_H_

#include <IndividualIPTVConfigurationDataApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "IptvConfigData.h"
#include "IptvConfigDataPatch.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class IndividualIPTVConfigurationDataApiImpl
    : public oai::udr::api::IndividualIPTVConfigurationDataApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  IndividualIPTVConfigurationDataApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~IndividualIPTVConfigurationDataApiImpl() {}

  void partial_replace_individual_iptv_configuration_data(
      const std::string& configurationId,
      const IptvConfigDataPatch& iptvConfigDataPatch,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
