/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IndividualExposureDataSubscriptionDocumentApiImpl.h"

#include "logger.hpp"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;

IndividualExposureDataSubscriptionDocumentApiImpl::
    IndividualExposureDataSubscriptionDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr, udr_app* udr_app_inst,
        std::string address)
    : IndividualExposureDataSubscriptionDocumentApi(rtr),
      m_udr_app(udr_app_inst),
      m_address(address) {}

void IndividualExposureDataSubscriptionDocumentApiImpl::
    delete_individual_exposure_data_subscription(
        const std::string& subId, Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void IndividualExposureDataSubscriptionDocumentApiImpl::
    replace_individual_exposure_data_subscription(
        const std::string& subId,
        const ExposureDataSubscription& exposureDataSubscription,
        Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace oai::udr::api
