/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* IndividualInfluenceDataSubscriptionDocumentApiImpl.h
*
* 
*/

#ifndef INDIVIDUAL_INFLUENCE_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_INFLUENCE_DATA_SUBSCRIPTION_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualInfluenceDataSubscriptionDocumentApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "TrafficInfluSub.h"
#include <string>

namespace oai::udr::api {

using namespace oai::udr::model;

class IndividualInfluenceDataSubscriptionDocumentApiImpl : public oai::udr::api::IndividualInfluenceDataSubscriptionDocumentApi {
public:
    IndividualInfluenceDataSubscriptionDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~IndividualInfluenceDataSubscriptionDocumentApiImpl() {}

    void delete_individual_influence_data_subscription(const std::string &subscriptionId, Pistache::Http::ResponseWriter &response);
    void read_individual_influence_data_subscription(const std::string &subscriptionId, Pistache::Http::ResponseWriter &response);
    void replace_individual_influence_data_subscription(const std::string &subscriptionId, const TrafficInfluSub &trafficInfluSub, Pistache::Http::ResponseWriter &response);

};

}






#endif