/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * InfluenceDataStoreApiImpl.h
 *
 *
 */

#ifndef INFLUENCE_DATA_STORE_API_IMPL_H_
#define INFLUENCE_DATA_STORE_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <InfluenceDataStoreApi.h>

#include <pistache/optional.h>

#include <string>
#include "ProblemDetails.h"
#include "Snssai.h"
#include "TrafficInfluData.h"

#include "udr_app.hpp"
namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class InfluenceDataStoreApiImpl : public oai::udr::api::InfluenceDataStoreApi {
 private:
  udr_app *m_udr_app;
  std::string m_address;

 public:
  InfluenceDataStoreApiImpl(std::shared_ptr<Pistache::Rest::Router>,
                            udr_app *udr_app_inst, std::string address);
  ~InfluenceDataStoreApiImpl() {}

  void read_influence_data(
      const Pistache::Optional<std::vector<std::string>> &influenceIds,
      const Pistache::Optional<std::vector<std::string>> &dnns,
      const Pistache::Optional<std::vector<Snssai>> &snssais,
      const Pistache::Optional<std::vector<std::string>> &internalGroupIds,
      const Pistache::Optional<std::vector<std::string>> &supis,
      const Pistache::Optional<std::string> &suppFeat,
      Pistache::Http::ResponseWriter &response);
};

}  // namespace oai::udr::api

#endif