/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * MessageWaitingDataDocumentApiImpl.h
 *
 *
 */

#ifndef MESSAGE_WAITING_DATA_DOCUMENT_API_IMPL_H_
#define MESSAGE_WAITING_DATA_DOCUMENT_API_IMPL_H_

#include <MessageWaitingDataDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include <vector>

#include "MessageWaitingData.h"
#include "PatchItem.h"
#include "udr_app.hpp"

namespace oai::udr::api {

class MessageWaitingDataDocumentApiImpl
    : public oai::udr::api::MessageWaitingDataDocumentApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  MessageWaitingDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~MessageWaitingDataDocumentApiImpl() {}

  void create_message_waiting_data(
      const std::string& ueId,
      const oai::udr::model::MessageWaitingData& messageWaitingData,
      Pistache::Http::ResponseWriter& response);
  void delete_message_waiting_data(
      const std::string& ueId, Pistache::Http::ResponseWriter& response);
  void modify_message_waiting_data(
      const std::string& ueId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      Pistache::Http::ResponseWriter& response);
  void query_message_waiting_data(
      const std::string& ueId,
      const Pistache::Optional<std::vector<std::string>>& fields,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
