/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MessageWaitingDataDocumentApiImpl.h"

#include "logger.hpp"
#include "udr_app.hpp"

namespace oai::udr::api {

MessageWaitingDataDocumentApiImpl::MessageWaitingDataDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    oai::udr::app::udr_app* udr_app_inst, std::string address)
    : MessageWaitingDataDocumentApi(rtr),
      m_udr_app(udr_app_inst),
      m_address(address) {}

void MessageWaitingDataDocumentApiImpl::create_message_waiting_data(
    const std::string& ueId,
    const oai::udr::model::MessageWaitingData& messageWaitingData,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void MessageWaitingDataDocumentApiImpl::delete_message_waiting_data(
    const std::string& ueId, Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void MessageWaitingDataDocumentApiImpl::modify_message_waiting_data(
    const std::string& ueId,
    const std::vector<oai::model::common::PatchItem>& patchItem,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void MessageWaitingDataDocumentApiImpl::query_message_waiting_data(
    const std::string& ueId,
    const Pistache::Optional<std::vector<std::string>>& fields,
    const Pistache::Optional<std::string>& supportedFeatures,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace oai::udr::api
