/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Modify5GVnGroupApiImpl.h
 *
 *
 */

#ifndef MODIFY5_G_VN_GROUP_API_IMPL_H_
#define MODIFY5_G_VN_GROUP_API_IMPL_H_

#include <Modify5GVnGroupApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include <vector>

#include "PatchItem.h"
#include "PatchResult.h"
#include "udr_app.hpp"

namespace oai::udr::api {

class Modify5GVnGroupApiImpl : public oai::udr::api::Modify5GVnGroupApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  Modify5GVnGroupApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~Modify5GVnGroupApiImpl() {}

  void modify5_g_vn_group(
      const std::string& externalGroupId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
