/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * OperatorSpecificDataContainerDocumentApiImpl.h
 *
 *
 */

#ifndef OPERATOR_SPECIFIC_DATA_CONTAINER_DOCUMENT_API_IMPL_H_
#define OPERATOR_SPECIFIC_DATA_CONTAINER_DOCUMENT_API_IMPL_H_

#include <OperatorSpecificDataContainerDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include <vector>

#include "OperatorSpecificDataContainer.h"
#include "PatchItem.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class OperatorSpecificDataContainerDocumentApiImpl
    : public oai::udr::api::OperatorSpecificDataContainerDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  OperatorSpecificDataContainerDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~OperatorSpecificDataContainerDocumentApiImpl() {}

  void modify_oper_spec_data(
      const std::string& ueId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
  void query_oper_spec_data(
      const std::string& ueId,
      const Pistache::Optional<std::vector<std::string>>& fields,
      const Pistache::Optional<std::string>& supportedFeatures,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifModifiedSince,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
