/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * OperatorSpecificDataDocumentApiImpl.h
 *
 *
 */

#ifndef OPERATOR_SPECIFIC_DATA_DOCUMENT_API_IMPL_H_
#define OPERATOR_SPECIFIC_DATA_DOCUMENT_API_IMPL_H_

#include "OperatorSpecificDataContainer.h"
#include "PatchItem.h"
#include "udr_app.hpp"
#include <OperatorSpecificDataDocumentApi.h>
#include <map>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <vector>

namespace oai::udr::api {

class OperatorSpecificDataDocumentApiImpl
    : public oai::udr::api::OperatorSpecificDataDocumentApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  OperatorSpecificDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~OperatorSpecificDataDocumentApiImpl() {}

  void read_operator_specific_data(
      const std::string& ueId,
      const Pistache::Optional<std::vector<std::string>>& fields,
      const Pistache::Optional<std::string>& suppFeat,
      Pistache::Http::ResponseWriter& response);
  void replace_operator_specific_data(
      const std::string& ueId,
      const std::map<
          std::string, oai::udr::model::OperatorSpecificDataContainer>&
          requestBody,
      Pistache::Http::ResponseWriter& response);
  void update_operator_specific_data(
      const std::string& ueId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
