/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ParameterProvisionDocumentApiImpl.h
*
* 
*/

#ifndef PARAMETER_PROVISION_DOCUMENT_API_IMPL_H_
#define PARAMETER_PROVISION_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ParameterProvisionDocumentApi.h>

#include <pistache/optional.h>

#include "PpData.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ParameterProvisionDocumentApiImpl : public org::openapitools::server::api::ParameterProvisionDocumentApi {
public:
    ParameterProvisionDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ParameterProvisionDocumentApiImpl() {}

    void getpp_data(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch, const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif