/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * PduSessionManagementDataApiImpl.h
 *
 *
 */

#ifndef PDU_SESSION_MANAGEMENT_DATA_API_IMPL_H_
#define PDU_SESSION_MANAGEMENT_DATA_API_IMPL_H_

#include <PduSessionManagementDataApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "Ipv6Prefix.h"
#include "PduSessionManagementData.h"
#include "udr_app.hpp"

namespace oai::udr::api {
class PduSessionManagementDataApiImpl
    : public oai::udr::api::PduSessionManagementDataApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  PduSessionManagementDataApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~PduSessionManagementDataApiImpl() {}

  void create_or_replace_session_management_data(
      const std::string& ueId, const int32_t& pduSessionId,
      const oai::udr::model::PduSessionManagementData& pduSessionManagementData,
      Pistache::Http::ResponseWriter& response);
  void delete_session_management_data(
      const std::string& ueId, const int32_t& pduSessionId,
      Pistache::Http::ResponseWriter& response);
  void query_session_management_data(
      const std::string& ueId, const int32_t& pduSessionId,
      const Pistache::Optional<std::string>& ipv4Addr,
      const Pistache::Optional<oai::model::common::Ipv6Prefix>& ipv6Prefix,
      const Pistache::Optional<std::string>& dnn,
      const Pistache::Optional<std::vector<std::string>>& fields,
      const Pistache::Optional<std::string>& suppFeat,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
