/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ProvisionedParameterDataDocumentApiImpl.h
 *
 *
 */

#ifndef PROVISIONED_PARAMETER_DATA_DOCUMENT_API_IMPL_H_
#define PROVISIONED_PARAMETER_DATA_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ProvisionedParameterDataDocumentApi.h>

#include <pistache/optional.h>

#include <string>
#include <vector>
#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"

#include "udr_app.hpp"
namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class ProvisionedParameterDataDocumentApiImpl
    : public oai::udr::api::ProvisionedParameterDataDocumentApi {
 private:
  udr_app *m_udr_app;
  std::string m_address;

 public:
  ProvisionedParameterDataDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app *udr_app_inst,
      std::string address);
  ~ProvisionedParameterDataDocumentApiImpl() {}

  void modify_pp_data(const std::string &ueId,
                      const std::vector<PatchItem> &patchItem,
                      const Pistache::Optional<std::string> &supportedFeatures,
                      Pistache::Http::ResponseWriter &response);
};

}  // namespace oai::udr::api

#endif