/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl.h
 *
 *
 */

#ifndef QUERY_NIDD_AUTHORIZATION_DATA_GPSI_OR_EXTERNAL_GROUP_IDENTIFIER_DOCUMENT_API_IMPL_H_
#define QUERY_NIDD_AUTHORIZATION_DATA_GPSI_OR_EXTERNAL_GROUP_IDENTIFIER_DOCUMENT_API_IMPL_H_

#include <QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "AuthorizationData.h"
#include "Snssai.h"
#include "udr_app.hpp"

namespace oai::udr::api {
class QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl
    : public oai::udr::api::
          QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~QueryNIDDAuthorizationDataGPSIOrExternalGroupIdentifierDocumentApiImpl() {}

  void get_nidd_au_data(
      const std::string& ueId,
      const Pistache::Optional<oai::model::common::Snssai>& singleNssai,
      const Pistache::Optional<std::string>& dnn,
      const Pistache::Optional<std::string>& mtcProviderInformation,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifModifiedSince,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
