/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* RetrievalOfSharedDataApiImpl.h
*
* 
*/

#ifndef RETRIEVAL_OF_SHARED_DATA_API_IMPL_H_
#define RETRIEVAL_OF_SHARED_DATA_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <RetrievalOfSharedDataApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
//#include "Set.h"
#include "SharedData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class RetrievalOfSharedDataApiImpl : public org::openapitools::server::api::RetrievalOfSharedDataApi {
public:
    RetrievalOfSharedDataApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~RetrievalOfSharedDataApiImpl() {}

//    void get_shared_data(const Pistache::Optional<Set<std::string>> &sharedDataIds, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif