/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SDMSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef SDM_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define SDM_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SDMSubscriptionDocumentApi.h>

#include <pistache/optional.h>

//#include "Object.h"
#include <string>
#include <vector>
#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include "SdmSubscription.h"

#include <mysql/mysql.h>

#include "udr_app.hpp"
namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class SDMSubscriptionDocumentApiImpl
    : public oai::udr::api::SDMSubscriptionDocumentApi {
 private:
  udr_app *m_udr_app;
  std::string m_address;

 public:
  SDMSubscriptionDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>,
                                 udr_app *udr_app_inst, std::string address,
                                 MYSQL *mysql);
  ~SDMSubscriptionDocumentApiImpl() {}

  void modifysdm_subscription(
      const std::string &ueId, const std::string &subsId,
      const std::vector<PatchItem> &patchItem,
      const Pistache::Optional<std::string> &supportedFeatures,
      Pistache::Http::ResponseWriter &response);
  void querysdm_subscription(const std::string &ueId, const std::string &subsId,
                             Pistache::Http::ResponseWriter &response);
  void removesdm_subscriptions(const std::string &ueId,
                               const std::string &subsId,
                               Pistache::Http::ResponseWriter &response);
  void updatesdmsubscriptions(const std::string &ueId,
                              const std::string &subsId,
                              SdmSubscription &sdmSubscription,
                              Pistache::Http::ResponseWriter &response);

 private:
  MYSQL *mysql_WitcommUDRDB;
};

}  // namespace oai::udr::api

#endif