/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SDMSubscriptionsCollectionApiImpl.h"

#include "logger.hpp"
#include "udr_app.hpp"
#include "udr_config.hpp"
using namespace config;
extern config::udr_config udr_cfg;
namespace oai::udr::api {

using namespace oai::udr::model;

SDMSubscriptionsCollectionApiImpl::SDMSubscriptionsCollectionApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udr_app *udr_app_inst,
    std::string address)
    : SDMSubscriptionsCollectionApi(rtr),
      m_udr_app(udr_app_inst),
      m_address(address) {}

void SDMSubscriptionsCollectionApiImpl::create_sdm_subscriptions(
    const std::string &ueId, SdmSubscription &sdmSubscription,
    Pistache::Http::ResponseWriter &response) {
  nlohmann::json response_data = {};
  Pistache::Http::Code code = {};
  m_udr_app->handle_create_sdm_subscriptions(ueId, sdmSubscription,
                                             response_data, code);

  Logger::udr_server().debug("HTTP reponse code %d.\n", code);
  response.send(code, response_data.dump());
}
void SDMSubscriptionsCollectionApiImpl::querysdmsubscriptions(
    const std::string &ueId,
    const Pistache::Optional<std::string> &supportedFeatures,
    Pistache::Http::ResponseWriter &response) {
  nlohmann::json response_data = {};
  Pistache::Http::Code code = {};
  m_udr_app->handle_query_sdm_subscriptions(ueId, response_data, code);

  Logger::udr_server().debug("HTTP reponse code %d.\n", code);
  response.send(code, response_data.dump());
}

}  // namespace oai::udr::api
