/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
*
* The version of the OpenAPI document: 2.1.2
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SDMSubscriptionsCollectionApiImpl.h
*
*
*/

#ifndef SDM_SUBSCRIPTIONS_COLLECTION_API_IMPL_H_
#define SDM_SUBSCRIPTIONS_COLLECTION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SDMSubscriptionsCollectionApi.h>

#include <pistache/optional.h>

#include "SdmSubscription.h"
#include <string>

#include <mysql/mysql.h>

namespace oai::udr::api {

using namespace oai::udr::model;

class SDMSubscriptionsCollectionApiImpl : public oai::udr::api::SDMSubscriptionsCollectionApi {
public:
    SDMSubscriptionsCollectionApiImpl(std::shared_ptr<Pistache::Rest::Router>, MYSQL *mysql);
    ~SDMSubscriptionsCollectionApiImpl() {}

    void create_sdm_subscriptions(const std::string &ueId, SdmSubscription &sdmSubscription, Pistache::Http::ResponseWriter &response);
    void querysdmsubscriptions(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response);
private:
    MYSQL *mysql_WitcommUDRDB;
};

}






#endif