/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SessionManagementSubscriptionDataApiImpl.h
 *
 *
 */

#ifndef SESSION_MANAGEMENT_SUBSCRIPTION_DATA_API_IMPL_H_
#define SESSION_MANAGEMENT_SUBSCRIPTION_DATA_API_IMPL_H_

#include <SessionManagementSubscriptionDataApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "SessionManagementSubscriptionData.h"
#include "Snssai.h"
#include "udr_app.hpp"

namespace oai::udr::api {

class SessionManagementSubscriptionDataApiImpl
    : public oai::udr::api::SessionManagementSubscriptionDataApi {
 private:
  oai::udr::app::udr_app* m_udr_app;
  std::string m_address;

 public:
  SessionManagementSubscriptionDataApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      oai::udr::app::udr_app* udr_app_inst, std::string address);
  ~SessionManagementSubscriptionDataApiImpl() {}

  void query_sm_data(
      const std::string& ueId, const std::string& servingPlmnId,
      const Pistache::Optional<oai::model::common::Snssai>& singleNssai,
      const Pistache::Optional<std::string>& dnn,
      const Pistache::Optional<std::vector<std::string>>& fields,
      const Pistache::Optional<std::string>& supportedFeatures,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifModifiedSince,
      Pistache::Http::ResponseWriter& response);
  void query_sm_data(Pistache::Http::ResponseWriter& response);
  void create_sm_data(
      const std::string& ueId, const std::string& servingPlmnId,
      oai::udr::model::SessionManagementSubscriptionData& subscriptionData,
      Pistache::Http::ResponseWriter& response);
  void put_sm_data(
      const std::string& ueId, const std::string& servingPlmnId,
      oai::udr::model::SessionManagementSubscriptionData& subscriptionData,
      Pistache::Http::ResponseWriter& response);
  void delete_sm_data(
      const std::string& ueId, const std::string& servingPlmnId,
      const Pistache::Optional<oai::model::common::Snssai>& singleNssai,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
