/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SMSSubscriptionDataDocumentApiImpl.h
*
* 
*/

#ifndef SMS_SUBSCRIPTION_DATA_DOCUMENT_API_IMPL_H_
#define SMS_SUBSCRIPTION_DATA_DOCUMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SMSSubscriptionDataDocumentApi.h>

#include <pistache/optional.h>

#include "SmsSubscriptionData.h"
#include <string>

namespace oai::udr::api {

using namespace oai::udr::model;

class SMSSubscriptionDataDocumentApiImpl : public oai::udr::api::SMSSubscriptionDataDocumentApi {
public:
    SMSSubscriptionDataDocumentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~SMSSubscriptionDataDocumentApiImpl() {}

    void query_sms_data(const std::string &ueId, const std::string &servingPlmnId, const Pistache::Optional<std::string> &supportedFeatures, const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch, const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince, Pistache::Http::ResponseWriter &response);

};

}






#endif