/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TraceDataDocumentApiImpl.h"

namespace oai::udr::api {

using namespace oai::udr::model;

TraceDataDocumentApiImpl::TraceDataDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr)
    : TraceDataDocumentApi(rtr) {}

void TraceDataDocumentApiImpl::query_trace_data(
    const std::string &ueId, const std::string &servingPlmnId,
    const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch,
    const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince,
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace oai::udr::model
