/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * UEPolicySetDocumentApiImpl.h
 *
 *
 */

#ifndef UE_POLICY_SET_DOCUMENT_API_IMPL_H_
#define UE_POLICY_SET_DOCUMENT_API_IMPL_H_

#include <UEPolicySetDocumentApi.h>
#include <pistache/http.h>
#include <pistache/optional.h>

#include "UePolicySet.h"
#include "UePolicySetPatch.h"
#include "udr_app.hpp"

namespace oai::udr::api {

using namespace oai::udr::model;
using namespace oai::udr::app;

class UEPolicySetDocumentApiImpl
    : public oai::udr::api::UEPolicySetDocumentApi {
 private:
  udr_app* m_udr_app;
  std::string m_address;

 public:
  UEPolicySetDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udr_app* udr_app_inst,
      std::string address);
  ~UEPolicySetDocumentApiImpl() {}

  void create_or_replace_ue_policy_set(
      const std::string& ueId, const UePolicySet& uePolicySet,
      Pistache::Http::ResponseWriter& response);
  void read_ue_policy_set(
      const std::string& ueId, const Pistache::Optional<std::string>& suppFeat,
      Pistache::Http::ResponseWriter& response);
  void update_ue_policy_set(
      const std::string& ueId, const UePolicySetPatch& uePolicySetPatch,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udr::api

#endif
