UDR = 
{
  INSTANCE_ID = 10;            # 0 is the default
  PID_DIRECTORY = "/var/run";   # /var/run is the default
  
  INTERFACES:
  {
    # UDR binded interface for Nudr interface
    NUDR: 
    {
      INTERFACE_NAME = "ens33";  			# YOUR NETWORK CONFIG HERE
      IPV4_ADDRESS   = "192.168.199.243";
      PORT           = 8081;                           	# YOUR NETWORK CONFIG HERE
    };
  };
  

  MYSQL:
  {
    ## MySQL mandatory options
    MYSQL_SERVER = "127.0.0.1"; # MySQL Server address
    MYSQL_USER   = "udr";   # Database server login
    MYSQL_PASS   = "udr123";   # Database server password
    MYSQL_DB     = "Witcomm-UDR-DB";     # Your database name
  };
};
