#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface UDR service
#   Valid for UBI 9.x | RHEL 9.x
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM registry.redhat.io/ubi9/ubi:latest AS oai-udr-builder

ARG EPEL_URL
ENV EPEL_URL=${EPEL_URL}

ENV IS_DOCKERFILE=1

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement

RUN rm -f /etc/rhsm-host && \
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms && \
    dnf update -y --allowerasing --skip-broken --nobest && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

ARG YQ_VERSION=v4.47.1
RUN case $(uname -m) in \
        x86_64)  YQ_BIN="yq_linux_amd64" ;; \
        aarch64) YQ_BIN="yq_linux_arm64" ;; \
        *) echo "Unsupported arch"; exit 1 ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BIN} -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

# 2024/05/24 : problem w/ cmake version 3.26.5-2
# Installing 2 versions on the system (3.20.2) and picking oldest one
WORKDIR /opt/cmake-3.20.2
RUN dnf install -y \
        wget \
        cmake && \
    wget --quiet https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-Linux-x86_64.sh \
        -O /tmp/cmake.sh && \
    sh /tmp/cmake.sh --prefix=/opt/cmake-3.20.2 --exclude-subdir && \
    rm -f /tmp/cmake.sh && \
    mv /usr/bin/cmake /usr/bin/cmake-3.26.5 && \
    ln -s /usr/bin/cmake-3.26.5 /usr/bin/cmake && \
    update-alternatives --install /usr/bin/cmake cmake /opt/cmake-3.20.2/bin/cmake 20 && \
    cmake --version && \
    dnf install -y wget cmake

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-udr
COPY . /openair-udr

# wait for it
WORKDIR /
RUN git clone https://github.com/vishnubob/wait-for-it.git

# Installing and Building UDR
WORKDIR /openair-udr/build/scripts
RUN ./build_udr --install-deps --force

# Patching the CMakefile to link mysqlclient
RUN sed -i -e "s@-lmysqlclient@-L/usr/lib64/mysql -lmysqlclient@" ../../src/oai_udr/CMakeLists.txt && \
    ./build_udr --clean --Verbose --build-type Release --jobs && \
    ldd /openair-udr/build/udr/build/udr && \
    mv /openair-udr/build/udr/build/udr /openair-udr/build/udr/build/oai_udr && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement


#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM registry.redhat.io/ubi9/ubi-minimal:latest as oai-udr
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement
# Copy the subscription manager configurations
COPY --from=oai-udr-builder /etc/rhsm /etc/rhsm
# We install some debug tools for the moment in addition of mandatory libraries
RUN rm -f /etc/rhsm-host && \
    microdnf update -y && \
    microdnf install -y \
# Debug Tools that are not mandatory
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      iputils \
      tcpdump \
# Mandatory packages for the NF to run
#      libasan \
      libicu \
      boost \
      utf8proc \
      libevent \
      findutils \
      libconfig && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement && \
    rm -rf /etc/rhsm

# Copying executable and generated libraries
WORKDIR /openair-udr/bin
COPY --from=oai-udr-builder \
    /openair-udr/build/udr/build/oai_udr \
    /openair-udr/scripts/healthcheck.sh \
    /wait-for-it/wait-for-it.sh \
    ./

COPY --from=oai-udr-builder /usr/local/bin/yq /usr/bin/yq


COPY --from=oai-udr-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
    /usr/local/lib64/libyaml-cpp.so.0.* \
    /usr/local/lib64/libcpr.so.1 \ 
    /usr/local/lib64/libmongocxx.so._noabi \
    /usr/local/lib64/libbsoncxx.so._noabi \
    /usr/lib64/mysql/libmysqlclient.so.21 \
    /lib64/libmongoc-1.0.so.0 \
    /lib64/libbson-1.0.so.0 \
    /lib64/libsnappy.so.1 \
    /lib64/libmongocrypt.so.0 \
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-udr/bin/oai_udr

WORKDIR /openair-udr/etc
COPY --from=oai-udr-builder \
    /openair-udr/etc/config.yaml ./

WORKDIR /openair-udr

# expose ports
EXPOSE 80/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-udr/bin/healthcheck.sh

CMD ["/openair-udr/bin/oai_udr", "-c", "/openair-udr/etc/config.yaml", "-o"]
