/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "QueryAMFSubscriptionInfoDocumentApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

QueryAMFSubscriptionInfoDocumentApi::QueryAMFSubscriptionInfoDocumentApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void QueryAMFSubscriptionInfoDocumentApi::init() {
    setupRoutes();
}

void QueryAMFSubscriptionInfoDocumentApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions", Routes::bind(&QueryAMFSubscriptionInfoDocumentApi::get_amf_subscription_info_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&QueryAMFSubscriptionInfoDocumentApi::query_amf_subscription_info_document_api_default_handler, this));
}

void QueryAMFSubscriptionInfoDocumentApi::get_amf_subscription_info_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueId = request.param(":ueId").as<std::string>();
    auto subsId = request.param(":subsId").as<std::string>();
    
    try {
      this->get_amf_subscription_info(ueId, subsId, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void QueryAMFSubscriptionInfoDocumentApi::query_amf_subscription_info_document_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

