#!/bin/bash

THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))

export OPENXGUDR_DIR=${THIS_SCRIPT_PATH%/*}

#echo "${THIS_SCRIPT_PATH%/*}"

if [ ! -d "/myfolder" ]; then
  mkdir $OPENXGUDR_DIR/build
fi

cd $OPENXGUDR_DIR/build
cmake $OPENXGUDR_DIR/src/
make -j4
