/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AccessAndMobilitySubscriptionDataDocumentApi.h"

#include "Helpers.h"
#include "logger.hpp"
#include "udr_config.hpp"
#include "udr_sbi_helper.hpp"

extern oai::udr::config::udr_config udr_cfg;

namespace oai::udr::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::udr::api;

AccessAndMobilitySubscriptionDataDocumentApi::
    AccessAndMobilitySubscriptionDataDocumentApi(
        std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
}

void AccessAndMobilitySubscriptionDataDocumentApi::init() {
  setupRoutes();
}

void AccessAndMobilitySubscriptionDataDocumentApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      udr_sbi_helper::UdrDataRepositoryServiceBase +
          udr_sbi_helper::UdrDrPathSubscriptionDataProvisionedDataAmData,
      Routes::bind(
          &AccessAndMobilitySubscriptionDataDocumentApi::query_am_data_handler,
          this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &AccessAndMobilitySubscriptionDataDocumentApi::
          access_and_mobility_subscription_data_document_api_default_handler,
      this));
}

void AccessAndMobilitySubscriptionDataDocumentApi::query_am_data_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  Logger::udr_server().info("AccessAndMobilitySubscriptionData Method: GET!");

  if (!request.hasParam(":ueId") or !request.hasParam(":servingPlmnId")) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request);
    return;
  }

  // Getting the path params
  auto ueId          = request.param(":ueId").as<std::string>();
  auto servingPlmnId = request.param(":servingPlmnId").as<std::string>();

  // Getting the query params
  auto fieldsQuery = request.query().get("fields");
  std::optional<std::vector<std::string>> fields;
  if (fieldsQuery.has_value()) {
    std::vector<std::string> valueQuery_instance;
    if (fromStringValue(fieldsQuery.value(), valueQuery_instance)) {
      fields = std::make_optional(valueQuery_instance);
    }
  }
  auto supportedFeaturesQuery = request.query().get("supported-features");
  std::optional<std::string> supportedFeatures;
  if (supportedFeaturesQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(supportedFeaturesQuery.value(), valueQuery_instance)) {
      supportedFeatures = std::make_optional(valueQuery_instance);
    }
  }

  // Getting the header params
  auto ifNoneMatch     = request.headers().tryGetRaw("If-None-Match");
  auto ifModifiedSince = request.headers().tryGetRaw("If-Modified-Since");

  try {
    this->query_am_data(
        ueId, servingPlmnId, fields, supportedFeatures, ifNoneMatch,
        ifModifiedSince, response);
  } catch (nlohmann::detail::exception& e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  } catch (Pistache::Http::HttpError& e) {
    response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
    return;
  } catch (std::exception& e) {
    // send a 500 error
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    return;
  }
}

void AccessAndMobilitySubscriptionDataDocumentApi::
    access_and_mobility_subscription_data_document_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::udr::api
