/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GroupIdentifiersApi.h"

#include "Helpers.h"
#include "udr_config.hpp"
#include "udr_sbi_helper.hpp"

extern oai::udr::config::udr_config udr_cfg;

namespace oai::udr::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::udr::api;

GroupIdentifiersApi::GroupIdentifiersApi(
    std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
}

void GroupIdentifiersApi::init() {
  setupRoutes();
}

void GroupIdentifiersApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      udr_sbi_helper::UdrDataRepositoryServiceBase +
          udr_sbi_helper::UdrDrPathSubscriptionDataGroupDataGroupIdentifier,
      Routes::bind(&GroupIdentifiersApi::get_group_identifiers_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &GroupIdentifiersApi::group_identifiers_api_default_handler, this));
}

void GroupIdentifiersApi::get_group_identifiers_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  // Getting the query params
  auto extGroupIdQuery = request.query().get("ext-group-id");
  std::optional<std::string> extGroupId;
  if (extGroupIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(extGroupIdQuery.value(), valueQuery_instance)) {
      extGroupId = std::make_optional(valueQuery_instance);
    }
  }
  auto intGroupIdQuery = request.query().get("int-group-id");
  std::optional<std::string> intGroupId;
  if (intGroupIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(intGroupIdQuery.value(), valueQuery_instance)) {
      intGroupId = std::make_optional(valueQuery_instance);
    }
  }
  auto ueIdIndQuery = request.query().get("ue-id-ind");
  std::optional<bool> ueIdInd;
  if (ueIdIndQuery.has_value()) {
    bool valueQuery_instance;
    if (fromStringValue(ueIdIndQuery.value(), valueQuery_instance)) {
      ueIdInd = std::make_optional(valueQuery_instance);
    }
  }
  auto supportedFeaturesQuery = request.query().get("supported-features");
  std::optional<std::string> supportedFeatures;
  if (supportedFeaturesQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(supportedFeaturesQuery.value(), valueQuery_instance)) {
      supportedFeatures = std::make_optional(valueQuery_instance);
    }
  }

  try {
    this->get_group_identifiers(
        extGroupId, intGroupId, ueIdInd, supportedFeatures, response);
  } catch (nlohmann::detail::exception& e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  } catch (Pistache::Http::HttpError& e) {
    response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
    return;
  } catch (std::exception& e) {
    // send a 500 error
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    return;
  }
}

void GroupIdentifiersApi::group_identifiers_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::udr::api
