/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * GroupIdentifiersApi.h
 *
 *
 */

#ifndef GroupIdentifiersApi_H_
#define GroupIdentifiersApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "GroupIdentifiers.h"

namespace oai::udr::api {

using namespace oai::udr::model;

class GroupIdentifiersApi {
 public:
  GroupIdentifiersApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~GroupIdentifiersApi() {}
  void init();

 private:
  void setupRoutes();

  void get_group_identifiers_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void group_identifiers_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Mapping of Group Identifiers
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="extGroupId">External Group Identifier (optional, default to
  /// &quot;&quot;)</param> <param name="intGroupId">Internal Group Identifier
  /// (optional, default to &quot;&quot;)</param> <param
  /// name="ueIdInd">Indication whether UE identifiers are required or not
  /// (optional, default to false)</param> <param
  /// name="supportedFeatures">Supported Features (optional, default to
  /// &quot;&quot;)</param>
  virtual void get_group_identifiers(
      const Pistache::Optional<std::string>& extGroupId,
      const Pistache::Optional<std::string>& intGroupId,
      const Pistache::Optional<bool>& ueIdInd,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::udr::api

#endif /* GroupIdentifiersApi_H_ */
