/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OperatorSpecificDataContainerDocumentApi.h
 *
 * 
 */

#ifndef OperatorSpecificDataContainerDocumentApi_H_
#define OperatorSpecificDataContainerDocumentApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "OperatorSpecificDataContainer.h"
#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include <string>
#include <vector>

namespace oai::udr::api {

using namespace oai::udr::model;

class  OperatorSpecificDataContainerDocumentApi {
public:
    OperatorSpecificDataContainerDocumentApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~OperatorSpecificDataContainerDocumentApi() {}
    void init();

    const std::string base = "/nudr-dr/v2";

private:
    void setupRoutes();

    void modify_oper_spec_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void query_oper_spec_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void operator_specific_data_container_document_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// To modify operator specific data of a UE
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">UE id</param>
    /// <param name="patchItem"></param>
    /// <param name="supportedFeatures">Features required to be supported by the target NF (optional, default to &quot;&quot;)</param>
    virtual void modify_oper_spec_data(const std::string &ueId, const std::vector<PatchItem> &patchItem, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Retrieves the operator specific data of a UE
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">UE id</param>
    /// <param name="fields">attributes to be retrieved (optional, default to std::vector&lt;std::string&gt;())</param>
    /// <param name="supportedFeatures">Supported Features (optional, default to &quot;&quot;)</param>
    /// <param name="ifNoneMatch">Validator for conditional requests, as described in RFC 7232, 3.2 (optional, default to &quot;&quot;)</param>
    /// <param name="ifModifiedSince">Validator for conditional requests, as described in RFC 7232, 3.3 (optional, default to &quot;&quot;)</param>
    virtual void query_oper_spec_data(const std::string &ueId, const Pistache::Optional<std::vector<std::string>> &fields, const Pistache::Optional<std::string> &supportedFeatures, const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch, const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince, Pistache::Http::ResponseWriter &response) = 0;

};

}




#endif /* OperatorSpecificDataContainerDocumentApi_H_ */

