# SPDX-License-Identifier: MIT

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "udr-build-cfg"
  namespace: oaicicd-core
spec:
    runPolicy: "Serial"
    source:
        type: "Binary"
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.udr.centos"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-udr:latest"
