/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AppDescriptor.h"

namespace oai::udr::model {

AppDescriptor::AppDescriptor() {
  m_OsId = "";
  m_OsIdIsSet = false;
  m_AppId = "";
  m_AppIdIsSet = false;
}

AppDescriptor::~AppDescriptor() {}

void AppDescriptor::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const AppDescriptor &o) {
  j = nlohmann::json();
  if (o.osIdIsSet())
    j["osId"] = o.m_OsId;
  if (o.appIdIsSet())
    j["appId"] = o.m_AppId;
}

void from_json(const nlohmann::json &j, AppDescriptor &o) {
  if (j.find("osId") != j.end()) {
    j.at("osId").get_to(o.m_OsId);
    o.m_OsIdIsSet = true;
  }
  if (j.find("appId") != j.end()) {
    j.at("appId").get_to(o.m_AppId);
    o.m_AppIdIsSet = true;
  }
}

std::string AppDescriptor::getOsId() const { return m_OsId; }
void AppDescriptor::setOsId(std::string const &value) {
  m_OsId = value;
  m_OsIdIsSet = true;
}
bool AppDescriptor::osIdIsSet() const { return m_OsIdIsSet; }
void AppDescriptor::unsetOsId() { m_OsIdIsSet = false; }
std::string AppDescriptor::getAppId() const { return m_AppId; }
void AppDescriptor::setAppId(std::string const &value) {
  m_AppId = value;
  m_AppIdIsSet = true;
}
bool AppDescriptor::appIdIsSet() const { return m_AppIdIsSet; }
void AppDescriptor::unsetAppId() { m_AppIdIsSet = false; }

} // namespace oai::udr::model
