/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * BackupAmfInfo.h
 *
 * 
 */

#ifndef BackupAmfInfo_H_
#define BackupAmfInfo_H_


#include <string>
#include <vector>
#include "Guami.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  BackupAmfInfo
{
public:
    BackupAmfInfo();
    virtual ~BackupAmfInfo();

    void validate();

    /////////////////////////////////////////////
    /// BackupAmfInfo members

    /// <summary>
    /// 
    /// </summary>
    std::string getBackupAmf() const;
    void setBackupAmf(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<Guami>& getGuamiList();
    void setGuamiList(std::vector<Guami> const& value);
    bool guamiListIsSet() const;
    void unsetGuamiList();

    friend void to_json(nlohmann::json& j, const BackupAmfInfo& o);
    friend void from_json(const nlohmann::json& j, BackupAmfInfo& o);
protected:
    std::string m_BackupAmf;

    std::vector<Guami> m_GuamiList;
    bool m_GuamiListIsSet;
};

}




#endif /* BackupAmfInfo_H_ */
