/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * BdtPolicyStatus.h
 *
 * Indicates the validation status of a negotiated BDT policy.
 */

#ifndef BdtPolicyStatus_H_
#define BdtPolicyStatus_H_


#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// Indicates the validation status of a negotiated BDT policy.
/// </summary>
class  BdtPolicyStatus
{
public:
    BdtPolicyStatus();
    virtual ~BdtPolicyStatus();

    void validate();

    /////////////////////////////////////////////
    /// BdtPolicyStatus members


    friend void to_json(nlohmann::json& j, const BdtPolicyStatus& o);
    friend void from_json(const nlohmann::json& j, BdtPolicyStatus& o);
protected:
};

}




#endif /* BdtPolicyStatus_H_ */
