/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EpsInterworkingInfo.h"

namespace oai::udr::model {

EpsInterworkingInfo::EpsInterworkingInfo() { m_EpsIwkPgwsIsSet = false; }

EpsInterworkingInfo::~EpsInterworkingInfo() {}

void EpsInterworkingInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const EpsInterworkingInfo &o) {
  j = nlohmann::json();
  if (o.epsIwkPgwsIsSet() || !o.m_EpsIwkPgws.empty())
    j["epsIwkPgws"] = o.m_EpsIwkPgws;
}

void from_json(const nlohmann::json &j, EpsInterworkingInfo &o) {
  if (j.find("epsIwkPgws") != j.end()) {
    j.at("epsIwkPgws").get_to(o.m_EpsIwkPgws);
    o.m_EpsIwkPgwsIsSet = true;
  }
}

std::map<std::string, EpsIwkPgw> &EpsInterworkingInfo::getEpsIwkPgws() {
  return m_EpsIwkPgws;
}
void EpsInterworkingInfo::setEpsIwkPgws(
    std::map<std::string, EpsIwkPgw> const &value) {
  m_EpsIwkPgws = value;
  m_EpsIwkPgwsIsSet = true;
}
bool EpsInterworkingInfo::epsIwkPgwsIsSet() const { return m_EpsIwkPgwsIsSet; }
void EpsInterworkingInfo::unsetEpsIwkPgws() { m_EpsIwkPgwsIsSet = false; }

} // namespace oai::udr::model
