/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EventType.h
 *
 * 
 */

#ifndef EventType_H_
#define EventType_H_


#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  EventType
{
public:
    EventType();
    virtual ~EventType();

    void validate();

    /////////////////////////////////////////////
    /// EventType members


    friend void to_json(nlohmann::json& j, const EventType& o);
    friend void from_json(const nlohmann::json& j, EventType& o);
protected:
};

}




#endif /* EventType_H_ */
