/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GroupIdentifiers.h
 *
 * 
 */

#ifndef GroupIdentifiers_H_
#define GroupIdentifiers_H_


#include "UeId.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  GroupIdentifiers
{
public:
    GroupIdentifiers();
    virtual ~GroupIdentifiers();

    void validate();

    /////////////////////////////////////////////
    /// GroupIdentifiers members

    /// <summary>
    /// 
    /// </summary>
    std::string getExtGroupId() const;
    void setExtGroupId(std::string const& value);
    bool extGroupIdIsSet() const;
    void unsetExtGroupId();
    /// <summary>
    /// 
    /// </summary>
    std::string getIntGroupId() const;
    void setIntGroupId(std::string const& value);
    bool intGroupIdIsSet() const;
    void unsetIntGroupId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<UeId>& getUeIdList();
    void setUeIdList(std::vector<UeId> const& value);
    bool ueIdListIsSet() const;
    void unsetUeIdList();

    friend void to_json(nlohmann::json& j, const GroupIdentifiers& o);
    friend void from_json(const nlohmann::json& j, GroupIdentifiers& o);
protected:
    std::string m_ExtGroupId;
    bool m_ExtGroupIdIsSet;
    std::string m_IntGroupId;
    bool m_IntGroupIdIsSet;
    std::vector<UeId> m_UeIdList;
    bool m_UeIdListIsSet;
};

}




#endif /* GroupIdentifiers_H_ */
