/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IdentityData.h
 *
 * 
 */

#ifndef IdentityData_H_
#define IdentityData_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  IdentityData
{
public:
    IdentityData();
    virtual ~IdentityData();

    void validate();

    /////////////////////////////////////////////
    /// IdentityData members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getSupiList();
    void setSupiList(std::vector<std::string> const& value);
    bool supiListIsSet() const;
    void unsetSupiList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getGpsiList();
    void setGpsiList(std::vector<std::string> const& value);
    bool gpsiListIsSet() const;
    void unsetGpsiList();

    friend void to_json(nlohmann::json& j, const IdentityData& o);
    friend void from_json(const nlohmann::json& j, IdentityData& o);
protected:
    std::vector<std::string> m_SupiList;
    bool m_SupiListIsSet;
    std::vector<std::string> m_GpsiList;
    bool m_GpsiListIsSet;
};

}




#endif /* IdentityData_H_ */
