/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IpSmGwRegistration.h
 *
 * 
 */

#ifndef IpSmGwRegistration_H_
#define IpSmGwRegistration_H_


#include "NetworkNodeDiameterAddress.h"
#include <string>
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  IpSmGwRegistration
{
public:
    IpSmGwRegistration();
    virtual ~IpSmGwRegistration();

    void validate();

    /////////////////////////////////////////////
    /// IpSmGwRegistration members

    /// <summary>
    /// 
    /// </summary>
    std::string getIpSmGwMapAddress() const;
    void setIpSmGwMapAddress(std::string const& value);
    bool ipSmGwMapAddressIsSet() const;
    void unsetIpSmGwMapAddress();
    /// <summary>
    /// 
    /// </summary>
    NetworkNodeDiameterAddress getIpSmGwDiameterAddress() const;
    void setIpSmGwDiameterAddress(NetworkNodeDiameterAddress const& value);
    bool ipSmGwDiameterAddressIsSet() const;
    void unsetIpSmGwDiameterAddress();
    /// <summary>
    /// 
    /// </summary>
    bool isUnriIndicator() const;
    void setUnriIndicator(bool const value);
    bool unriIndicatorIsSet() const;
    void unsetUnriIndicator();

    friend void to_json(nlohmann::json& j, const IpSmGwRegistration& o);
    friend void from_json(const nlohmann::json& j, IpSmGwRegistration& o);
protected:
    std::string m_IpSmGwMapAddress;
    bool m_IpSmGwMapAddressIsSet;
    NetworkNodeDiameterAddress m_IpSmGwDiameterAddress;
    bool m_IpSmGwDiameterAddressIsSet;
    bool m_UnriIndicator;
    bool m_UnriIndicatorIsSet;
};

}




#endif /* IpSmGwRegistration_H_ */
