/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LcsBroadcastAssistanceTypesData.h"

namespace oai::udr::model {

LcsBroadcastAssistanceTypesData::LcsBroadcastAssistanceTypesData() {}

LcsBroadcastAssistanceTypesData::~LcsBroadcastAssistanceTypesData() {}

void LcsBroadcastAssistanceTypesData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const LcsBroadcastAssistanceTypesData &o) {
  j = nlohmann::json();
  j["locationAssistanceType"] = o.m_LocationAssistanceType;
}

void from_json(const nlohmann::json &j, LcsBroadcastAssistanceTypesData &o) {
  j.at("locationAssistanceType").get_to(o.m_LocationAssistanceType);
}

std::vector<std::string> &
LcsBroadcastAssistanceTypesData::getLocationAssistanceType() {
  return m_LocationAssistanceType;
}
void LcsBroadcastAssistanceTypesData::setLocationAssistanceType(
    std::vector<std::string> const &value) {
  m_LocationAssistanceType = value;
}

} // namespace oai::udr::model
