/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LcsClientClass.h"

namespace oai::udr::model {

LcsClientClass::LcsClientClass() {}

LcsClientClass::~LcsClientClass() {}

void LcsClientClass::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const LcsClientClass &o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json &j, LcsClientClass &o) {}

} // namespace oai::udr::model
