/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Lpi.h
 *
 * 
 */

#ifndef Lpi_H_
#define Lpi_H_


#include "ValidTimePeriod.h"
#include "LocationPrivacyInd.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  Lpi
{
public:
    Lpi();
    virtual ~Lpi();

    void validate();

    /////////////////////////////////////////////
    /// Lpi members

    /// <summary>
    /// 
    /// </summary>
    LocationPrivacyInd getLocationPrivacyInd() const;
    void setLocationPrivacyInd(LocationPrivacyInd const& value);
    /// <summary>
    /// 
    /// </summary>
    ValidTimePeriod getValidTimePeriod() const;
    void setValidTimePeriod(ValidTimePeriod const& value);
    bool validTimePeriodIsSet() const;
    void unsetValidTimePeriod();

    friend void to_json(nlohmann::json& j, const Lpi& o);
    friend void from_json(const nlohmann::json& j, Lpi& o);
protected:
    LocationPrivacyInd m_LocationPrivacyInd;

    ValidTimePeriod m_ValidTimePeriod;
    bool m_ValidTimePeriodIsSet;
};

}




#endif /* Lpi_H_ */
