/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OperatorSpecificDataContainer.h
 *
 * 
 */

#ifndef OperatorSpecificDataContainer_H_
#define OperatorSpecificDataContainer_H_


#include <string>
//#include "OneOfstringintegernumberbooleanobject.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  OperatorSpecificDataContainer
{
public:
    OperatorSpecificDataContainer();
    virtual ~OperatorSpecificDataContainer();

    void validate();

    /////////////////////////////////////////////
    /// OperatorSpecificDataContainer members

    /// <summary>
    /// 
    /// </summary>
    std::string getDataType() const;
    void setDataType(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getDataTypeDefinition() const;
    void setDataTypeDefinition(std::string const& value);
    bool dataTypeDefinitionIsSet() const;
    void unsetDataTypeDefinition();
    /// <summary>
    /// 
    /// </summary>
//    OneOfstringintegernumberbooleanobject getValue() const;
//    void setValue(OneOfstringintegernumberbooleanobject const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

    friend void to_json(nlohmann::json& j, const OperatorSpecificDataContainer& o);
    friend void from_json(const nlohmann::json& j, OperatorSpecificDataContainer& o);
protected:
    std::string m_DataType;

    std::string m_DataTypeDefinition;
    bool m_DataTypeDefinitionIsSet;
//    OneOfstringintegernumberbooleanobject m_Value;

    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}




#endif /* OperatorSpecificDataContainer_H_ */
