/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PatchResult.h
 *
 * 
 */

#ifndef PatchResult_H_
#define PatchResult_H_


#include "ReportItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  PatchResult
{
public:
    PatchResult();
    virtual ~PatchResult();

    void validate();

    /////////////////////////////////////////////
    /// PatchResult members

    /// <summary>
    /// 
    /// </summary>
    std::vector<ReportItem>& getReport();
    void setReport(std::vector<ReportItem> const& value);

    friend void to_json(nlohmann::json& j, const PatchResult& o);
    friend void from_json(const nlohmann::json& j, PatchResult& o);
protected:
    std::vector<ReportItem> m_Report;

};

}




#endif /* PatchResult_H_ */
