/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PduSessionStatusCfg.h"

namespace oai::udr::model {

PduSessionStatusCfg::PduSessionStatusCfg() {
  m_Dnn = "";
  m_DnnIsSet = false;
}

PduSessionStatusCfg::~PduSessionStatusCfg() {}

void PduSessionStatusCfg::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const PduSessionStatusCfg &o) {
  j = nlohmann::json();
  if (o.dnnIsSet())
    j["dnn"] = o.m_Dnn;
}

void from_json(const nlohmann::json &j, PduSessionStatusCfg &o) {
  if (j.find("dnn") != j.end()) {
    j.at("dnn").get_to(o.m_Dnn);
    o.m_DnnIsSet = true;
  }
}

std::string PduSessionStatusCfg::getDnn() const { return m_Dnn; }
void PduSessionStatusCfg::setDnn(std::string const &value) {
  m_Dnn = value;
  m_DnnIsSet = true;
}
bool PduSessionStatusCfg::dnnIsSet() const { return m_DnnIsSet; }
void PduSessionStatusCfg::unsetDnn() { m_DnnIsSet = false; }

} // namespace oai::udr::model
