/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PlmnIdNid.h
 *
 * 
 */

#ifndef PlmnIdNid_H_
#define PlmnIdNid_H_


#include <string>
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  PlmnIdNid
{
public:
    PlmnIdNid();
    virtual ~PlmnIdNid();

    void validate();

    /////////////////////////////////////////////
    /// PlmnIdNid members

    /// <summary>
    /// 
    /// </summary>
    std::string getMcc() const;
    void setMcc(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getMnc() const;
    void setMnc(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getNid() const;
    void setNid(std::string const& value);
    bool nidIsSet() const;
    void unsetNid();

    friend void to_json(nlohmann::json& j, const PlmnIdNid& o);
    friend void from_json(const nlohmann::json& j, PlmnIdNid& o);
protected:
    std::string m_Mcc;

    std::string m_Mnc;

    std::string m_Nid;
    bool m_NidIsSet;
};

}




#endif /* PlmnIdNid_H_ */
