/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Polygon.h
 *
 * 
 */

#ifndef Polygon_H_
#define Polygon_H_


#include "GeographicalCoordinates.h"
#include "GADShape.h"
#include <vector>
#include "Polygon_allOf.h"
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  Polygon
{
public:
    Polygon();
    virtual ~Polygon();

    void validate();

    /////////////////////////////////////////////
    /// Polygon members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<GeographicalCoordinates>& getPointList();
    void setPointList(std::vector<GeographicalCoordinates> const& value);

    friend void to_json(nlohmann::json& j, const Polygon& o);
    friend void from_json(const nlohmann::json& j, Polygon& o);
protected:
    SupportedGADShapes m_Shape;

    std::vector<GeographicalCoordinates> m_PointList;

};

}




#endif /* Polygon_H_ */
