/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SmsfInfo.h
 *
 * 
 */

#ifndef SmsfInfo_H_
#define SmsfInfo_H_


#include <string>
#include "PlmnId.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  SmsfInfo
{
public:
    SmsfInfo();
    virtual ~SmsfInfo();

    void validate();

    /////////////////////////////////////////////
    /// SmsfInfo members

    /// <summary>
    /// 
    /// </summary>
    std::string getSmsfInstanceId() const;
    void setSmsfInstanceId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    PlmnId getPlmnId() const;
    void setPlmnId(PlmnId const& value);

    friend void to_json(nlohmann::json& j, const SmsfInfo& o);
    friend void from_json(const nlohmann::json& j, SmsfInfo& o);
protected:
    std::string m_SmsfInstanceId;

    PlmnId m_PlmnId;

};

}




#endif /* SmsfInfo_H_ */
