/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SponsorConnectivityData.h"

namespace oai::udr::model {

SponsorConnectivityData::SponsorConnectivityData() {}

SponsorConnectivityData::~SponsorConnectivityData() {}

void SponsorConnectivityData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const SponsorConnectivityData &o) {
  j = nlohmann::json();
  j["aspIds"] = o.m_AspIds;
}

void from_json(const nlohmann::json &j, SponsorConnectivityData &o) {
  j.at("aspIds").get_to(o.m_AspIds);
}

std::vector<std::string> &SponsorConnectivityData::getAspIds() {
  return m_AspIds;
}
void SponsorConnectivityData::setAspIds(std::vector<std::string> const &value) {
  m_AspIds = value;
}

} // namespace oai::udr::model
