/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscribedEvent.h
 *
 * Possible values are - UP_PATH_CHANGE: The AF requests to be notified when the UP path changes for the PDU session. 
 */

#ifndef SubscribedEvent_H_
#define SubscribedEvent_H_


#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// Possible values are - UP_PATH_CHANGE: The AF requests to be notified when the UP path changes for the PDU session. 
/// </summary>
class  SubscribedEvent
{
public:
    SubscribedEvent();
    virtual ~SubscribedEvent();

    void validate();

    /////////////////////////////////////////////
    /// SubscribedEvent members


    friend void to_json(nlohmann::json& j, const SubscribedEvent& o);
    friend void from_json(const nlohmann::json& j, SubscribedEvent& o);
protected:
};

}




#endif /* SubscribedEvent_H_ */
