/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeContextInSmfData.h
 *
 * 
 */

#ifndef UeContextInSmfData_H_
#define UeContextInSmfData_H_


#include "PgwInfo.h"
#include "EmergencyInfo.h"
#include <map>
#include <vector>
#include "PduSession.h"
#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  UeContextInSmfData
{
public:
    UeContextInSmfData();
    virtual ~UeContextInSmfData();

    void validate();

    /////////////////////////////////////////////
    /// UeContextInSmfData members

    /// <summary>
    /// A map (list of key-value pairs where PduSessionId serves as key) of PduSessions
    /// </summary>
    std::map<std::string, PduSession>& getPduSessions();
    void setPduSessions(std::map<std::string, PduSession> const& value);
    bool pduSessionsIsSet() const;
    void unsetPduSessions();
    /// <summary>
    /// 
    /// </summary>
    std::vector<PgwInfo>& getPgwInfo();
    void setPgwInfo(std::vector<PgwInfo> const& value);
    bool pgwInfoIsSet() const;
    void unsetPgwInfo();
    /// <summary>
    /// 
    /// </summary>
    EmergencyInfo getEmergencyInfo() const;
    void setEmergencyInfo(EmergencyInfo const& value);
    bool emergencyInfoIsSet() const;
    void unsetEmergencyInfo();

    friend void to_json(nlohmann::json& j, const UeContextInSmfData& o);
    friend void from_json(const nlohmann::json& j, UeContextInSmfData& o);
protected:
    std::map<std::string, PduSession> m_PduSessions;
    bool m_PduSessionsIsSet;
    std::vector<PgwInfo> m_PgwInfo;
    bool m_PgwInfoIsSet;
    EmergencyInfo m_EmergencyInfo;
    bool m_EmergencyInfoIsSet;
};

}




#endif /* UeContextInSmfData_H_ */
