/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeReachability.h
 *
 * 
 */

#ifndef UeReachability_H_
#define UeReachability_H_


#include <nlohmann/json.hpp>

namespace oai::udr::model {

/// <summary>
/// 
/// </summary>
class  UeReachability
{
public:
    UeReachability();
    virtual ~UeReachability();

    void validate();

    /////////////////////////////////////////////
    /// UeReachability members


    friend void to_json(nlohmann::json& j, const UeReachability& o);
    friend void from_json(const nlohmann::json& j, UeReachability& o);
protected:
};

}




#endif /* UeReachability_H_ */
