/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UncertaintyEllipse.h"

namespace oai::udr::model {

UncertaintyEllipse::UncertaintyEllipse() {
  m_SemiMajor = 0.0f;
  m_SemiMinor = 0.0f;
  m_OrientationMajor = 0;
}

UncertaintyEllipse::~UncertaintyEllipse() {}

void UncertaintyEllipse::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const UncertaintyEllipse &o) {
  j = nlohmann::json();
  j["semiMajor"] = o.m_SemiMajor;
  j["semiMinor"] = o.m_SemiMinor;
  j["orientationMajor"] = o.m_OrientationMajor;
}

void from_json(const nlohmann::json &j, UncertaintyEllipse &o) {
  j.at("semiMajor").get_to(o.m_SemiMajor);
  j.at("semiMinor").get_to(o.m_SemiMinor);
  j.at("orientationMajor").get_to(o.m_OrientationMajor);
}

float UncertaintyEllipse::getSemiMajor() const { return m_SemiMajor; }
void UncertaintyEllipse::setSemiMajor(float const value) {
  m_SemiMajor = value;
}
float UncertaintyEllipse::getSemiMinor() const { return m_SemiMinor; }
void UncertaintyEllipse::setSemiMinor(float const value) {
  m_SemiMinor = value;
}
int32_t UncertaintyEllipse::getOrientationMajor() const {
  return m_OrientationMajor;
}
void UncertaintyEllipse::setOrientationMajor(int32_t const value) {
  m_OrientationMajor = value;
}

} // namespace oai::udr::model
