/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Class5GVNGroupsStoreApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

Class5GVNGroupsStoreApi::Class5GVNGroupsStoreApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void Class5GVNGroupsStoreApi::init() {
    setupRoutes();
}

void Class5GVNGroupsStoreApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/subscription-data/group-data/5g-vn-groups", Routes::bind(&Class5GVNGroupsStoreApi::query5_g_vn_group_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&Class5GVNGroupsStoreApi::class5_gvn_groups_store_api_default_handler, this));
}

void Class5GVNGroupsStoreApi::query5_g_vn_group_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto gpsisQuery = request.query().get("gpsis");
    Pistache::Optional<std::vector<std::string>> gpsis;
    if(!gpsisQuery.isEmpty()){
        std::vector<std::string> valueQuery_instance;
        if(fromStringValue(gpsisQuery.get(), valueQuery_instance)){
            gpsis = Pistache::Some(valueQuery_instance);
        }
    }
    
    try {
      this->query5_g_vn_group(gpsis, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void Class5GVNGroupsStoreApi::class5_gvn_groups_store_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

