/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ContextDataDocumentApi.h
 *
 * 
 */

#ifndef ContextDataDocumentApi_H_
#define ContextDataDocumentApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ContextDataSetName.h"
#include "ContextDataSets.h"
#include "Set.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  ContextDataDocumentApi {
public:
    ContextDataDocumentApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~ContextDataDocumentApi() {}
    void init();

    const std::string base = "/nudr-dr/v2";

private:
    void setupRoutes();

    void query_context_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void context_data_document_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Retrieve multiple context data sets of a UE
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">UE id</param>
    /// <param name="contextDatasetNames">List of context dataset names</param>
    virtual void query_context_data(const std::string &ueId, const Pistache::Optional<Set<ContextDataSetName>> &contextDatasetNames, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* ContextDataDocumentApi_H_ */

