/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "EventExposureDataDocumentApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

EventExposureDataDocumentApi::EventExposureDataDocumentApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void EventExposureDataDocumentApi::init() {
    setupRoutes();
}

void EventExposureDataDocumentApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/subscription-data/:ueId/ee-profile-data", Routes::bind(&EventExposureDataDocumentApi::query_ee_data_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&EventExposureDataDocumentApi::event_exposure_data_document_api_default_handler, this));
}

void EventExposureDataDocumentApi::query_ee_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueId = request.param(":ueId").as<std::string>();
    
    // Getting the query params
    auto fieldsQuery = request.query().get("fields");
    Pistache::Optional<std::vector<std::string>> fields;
    if(!fieldsQuery.isEmpty()){
        std::vector<std::string> valueQuery_instance;
        if(fromStringValue(fieldsQuery.get(), valueQuery_instance)){
            fields = Pistache::Some(valueQuery_instance);
        }
    }
    auto supportedFeaturesQuery = request.query().get("supportedFeatures");
    Pistache::Optional<std::string> supportedFeatures;
    if(!supportedFeaturesQuery.isEmpty()){
        std::string valueQuery_instance;
        if(fromStringValue(supportedFeaturesQuery.get(), valueQuery_instance)){
            supportedFeatures = Pistache::Some(valueQuery_instance);
        }
    }
    
    try {
      this->query_ee_data(ueId, fields, supportedFeatures, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void EventExposureDataDocumentApi::event_exposure_data_document_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

