/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IndividualBDTPolicyDataDocumentApi.h
 *
 * 
 */

#ifndef IndividualBDTPolicyDataDocumentApi_H_
#define IndividualBDTPolicyDataDocumentApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "BdtPolicyData.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  IndividualBDTPolicyDataDocumentApi {
public:
    IndividualBDTPolicyDataDocumentApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~IndividualBDTPolicyDataDocumentApi() {}
    void init();

    const std::string base = "/nudr-dr/v2";

private:
    void setupRoutes();

    void create_individual_applied_bdt_policy_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void individual_bdt_policy_data_document_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Create an individual applied BDT Policy Data resource
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="bdtPolicyId">The Identifier of an Individual Applied BDT Policy Data to be created or updated. It shall apply the format of Data type string.</param>
    /// <param name="bdtPolicyData"></param>
    virtual void create_individual_applied_bdt_policy_data(const std::string &bdtPolicyId, const BdtPolicyData &bdtPolicyData, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* IndividualBDTPolicyDataDocumentApi_H_ */

