/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.2.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UEPolicySetDocumentApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

UEPolicySetDocumentApi::UEPolicySetDocumentApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void UEPolicySetDocumentApi::init() {
    setupRoutes();
}

void UEPolicySetDocumentApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Put(*router, base + "/policy-data/ues/:ueId/ue-policy-set", Routes::bind(&UEPolicySetDocumentApi::create_or_replace_ue_policy_set_handler, this));
    Routes::Get(*router, base + "/policy-data/ues/:ueId/ue-policy-set", Routes::bind(&UEPolicySetDocumentApi::read_ue_policy_set_handler, this));
    Routes::Patch(*router, base + "/policy-data/ues/:ueId/ue-policy-set", Routes::bind(&UEPolicySetDocumentApi::update_ue_policy_set_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&UEPolicySetDocumentApi::ue_policy_set_document_api_default_handler, this));
}

void UEPolicySetDocumentApi::create_or_replace_ue_policy_set_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueId = request.param(":ueId").as<std::string>();
    
    // Getting the body param
    
    UePolicySet uePolicySet;
    
    try {
      nlohmann::json::parse(request.body()).get_to(uePolicySet);
      this->create_or_replace_ue_policy_set(ueId, uePolicySet, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}
void UEPolicySetDocumentApi::read_ue_policy_set_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueId = request.param(":ueId").as<std::string>();
    
    // Getting the query params
    auto suppFeatQuery = request.query().get("supp-feat");
    Pistache::Optional<std::string> suppFeat;
    if(!suppFeatQuery.isEmpty()){
        std::string valueQuery_instance;
        if(fromStringValue(suppFeatQuery.get(), valueQuery_instance)){
            suppFeat = Pistache::Some(valueQuery_instance);
        }
    }
    
    try {
      this->read_ue_policy_set(ueId, suppFeat, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}
void UEPolicySetDocumentApi::update_ue_policy_set_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueId = request.param(":ueId").as<std::string>();
    
    // Getting the body param
    
    UePolicySetPatch uePolicySetPatch;
    
    try {
      nlohmann::json::parse(request.body()).get_to(uePolicySetPatch);
      this->update_ue_policy_set(ueId, uePolicySetPatch, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (Pistache::Http::HttpError &e) {
        response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void UEPolicySetDocumentApi::ue_policy_set_document_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

